### PR TITLE
feat: Added Dify template

### PR DESCRIPTION
**Pull request by OhThatMatt**
I've added a template for [Dify](https://github.com/langgenius/dify), but I'm running into couple of issues. 

1. **Postgres Password/User Generation:**

- [x] I'm having trouble generating the Postgres password and user. When attempting to do this with `$SERVICE`, it messes up other parts of the configuration, leading to issues where the credentials cannot be found. 

2. **API Server Name Issue:**

- [x] The API server is currently appearing as a random string. It needs to be set in the ENV variables, but it has to match the public URL. 

3. **Health Checks on Services:**

- [x] Health checking is not implemented for all services, resulting in some containers reporting as unhealthy, even though they are functioning correctly.

4. **Redis Service Variables:**

- [x] The `SERVICE_USER_REDIS` and `SERVICE_PASSWORD_REDIS` variables are defaulting to blank strings during deployments. Despite being set and visible in the ENV variables, they cannot be found during deployment.

Dify supports a variety of vector databases, and you can change them by setting an environment variable. However, this approach causes problems because each container is still created regardless of the ENV variable, leading to deployment failures. As a workaround, I removed all but the default database. I’m open to suggestions on a better way to handle this.

The original `docker-compose` can be found here: [docker-compose.yaml](https://github.com/langgenius/dify/tree/main/docker)

### CODE REVIEW

**Comment by OhThatMatt** [comment]
Updated the commit with improvements on the original PR.

**Comment by rennokki** [comment]
LGTM!

**Comment by lei-cao** [comment]
wow! when will this be released?

**Comment by OhThatMatt** [comment]
@lei-cao 

The other PR for AI related templates has been merged yesterday (#2980) I hope that this one will get reviewed soon.

**Comment by rennokki** [comment]
@andrasbacsai

**Comment by peaklabs-dev** [comment]
Thank you for the PR 💜. I will test it and fix it if necessary.

**Comment by ekiwi111** [comment]
I'm getting a 404 error from `/console/api/setup` on the `/install` page when running Dify with the Docker Compose template. Is there any additional configuration I need to add?

**Comment by Deyvi-dev** [comment]
I noticed that the Dify template was added in release v4.0.0-beta.361; however, it’s missing from the `templates/service-templates.json` file.

**Pull request merged**
