### PR TITLE
Fix Vaultwarden + Add Configs

### PR DESCRIPTION
**Pull request by iamEvanYT**
This adds some new Environment Variables to Vaultwarden + Required ones (e.g: `DOMAIN`)
This commit had been tested.
Screenshot 2024-05-27 at 8 54 21 AM

There is one problem. If the `SMTP_HOST` has been set but is empty, the service will refuse to start up.
Do we create two separate services with mail and without, or how would you solve it?

### CODE REVIEW

**Comment by compgeniuses** [comment]
how about defining some default placeholder values for the SMTP host to solve the problems experienced.

**Comment by iamEvanYT** [comment]
> how about defining some default placeholder values for the SMTP host to solve the problems experienced.
> 
> 

However, that will make Vaultwarden thinks it is able to send emails, leading to some unexpected behaviours, like when it asks the user to verify their email.

**Comment by compgeniuses** [comment]
is email verification enabled by default?

**Comment by iamEvanYT** [comment]
> is email verification enabled by default?

It wouldn't be, if `SMTP_HOST` isn't specified.

**Comment by iamEvanYT** [comment]
Found a solution. The SMTP server can be set manually in the admin panel (vaultwarden.example.com/admin), so I'll remove it in the Environment Variables.

**Comment by andrasbacsai** [comment]
Thank you for the PR!

**Pull request merged**
