### PR TITLE
Add oauth support

### PR DESCRIPTION
**Pull request by procchio6**
- Support azure, bitbucket, github, gitlab, google providers
- Add authentication page to settings

image

image

Refs:
#1755
#1255

### CODE REVIEW

**Comment by compgeniuses** [comment]
interesting, i was just thinking about implementation of Ldap and OIDC for coolify, and then boom, here we are.

Similalry i saw another PR implementing other things that were on my mind, Has my brain been hacked by coolify?!

**Comment by compgeniuses** [comment]
@procchio6 my Appologies.

WOuld you kindly consider Implementing IDP providers into this PR as additional authentications.

This is because, by implementing IDP providers, we Automatically would support other authentication systems like OIDC, SAML and possibly LDap for those that support it.

We could have

Authentik
Auth0
Jumplcloud
KanIDM
Okta

What do you think?

**Comment by andrasbacsai** [comment]
@compgeniuses With all respect, please do not ask for additional things in a PR without involving me.

@procchio6 Huge thanks for the implementation, I will check and let you know how to procced.

**Comment by compgeniuses** [comment]
@andrasbacsai that's why i began with apologies. again my apologies.

**Pull request merged**
