### PR TITLE
UI Improvements and minor responsiveness fixes 👍

### PR DESCRIPTION
**Pull request by LLxD**
Hey! Found a few responsiveness problems and this PR addresses them! In terms of issue, it address (at least part of) the problem described [here](https://github.com/coollabsio/coolify/issues/458).

I'll probably keep working on responsiveness improvements since there are a few to be made, and I'll creating new PR's as I make progress.

Before:
image
image
image

After:
image
image
image

### CODE REVIEW

**Comment by andrasbacsai** [comment]
Thanks for the PR! 👍🏻 It looks super awesome!

Unfortunately, I changed the dashboard since, so I cannot merge your changes as there are conflicts (but I do not see them on GitHub).

Can you please resolve them?

**Comment by LLxD** [comment]
Of course! As soon as they are resolved, I'll let you know! 

Also nice job with the updates as always :rocket:

**Comment by LLxD** [comment]
Hey! Fixed the conflicts 💯 

Took the opportunity to fix the register screen to (on mobile screens). Here are a few pictures 🚀 

image
image
image
image

**Comment by hdbham** [comment]
I found a few more.

Rather than find every relative path, i'll name the pages using h1 and means of navigation. 
I likely wont catch everything on first go,

## Subtasks

#### Dashboard
- [ ] update breakpoint prefixes for elements under _"Resources"_  so no longer collides with with nav. 
- >  changing height and width of icons helps, but padding may need to change 

- [ ] update breakpoint prefixes for elements under _"Hardware Details"_ , `stat-value` 
- > padding may be unnecessary on mobile, _"Load Average"_ uncenters under 400px if all values above 2 digits

#### App > Configuration
- [ ] h1 collides with nav-side
- [ ] fix padding/centering for inputs  
- > change padding

####  Gitlab > Configuration
- [ ] `<div class="p-2 text-xs text-stone-400 w-full">` collides with nav

#### Docker > destinations
- [ ] fix padding/centering for inputs

#### General database configuration 
- [ ] copy svg not aligned right

**Pull request merged**
