### PR TITLE
feat: add ntfy notifications

### PR DESCRIPTION
**Pull request by frostplexx**
This PR adds support for [ntfy.sh](https://ntfy.sh/) notifications.

### CODE REVIEW

**Comment by Lukap22** [comment]
I need this!

**Comment by vinicius507** [comment]
What are the plans for this integration?

**Comment by peaklabs-dev** [comment]
@frostplexx Sorry for the late review. I have completed the refactored notifications for the next release and if you still have time and are able to work on this PR, it would be necessary to adjust your PR according to the new notification handling. You can check my PR to see the migrations and models added: https://github.com/coollabsio/coolify/pull/4525 and you can check out the `next` branch for now to see the new way of implementing notifications. 

It would be great if you could adjust your PR accordingly. If you are unable to do so, please let me know so I can close this PR.

**Comment by compgeniuses** [comment]
the new refactored notifications is superb

**Comment by peaklabs-dev** [comment]
Thank you for your contribution. Due to inactivity, we're closing this PR. If you'd like to revisit this change, feel free to reopen this PR or open a new pull request. (or maybe I will have integrated NTFY notifications by then)

**Pull request closed without merging**
