### PR TITLE
Add API Endpoints for GitHub integration for app creation, repository, and branch management 

### PR DESCRIPTION
**Pull request by xmahbub**
Add GitHub controller to manage GitHub apps, repositories, and branches

- New routes for GitHub app management:
  - `POST /github-apps`: Create a new GitHub app
  - `GET /github-apps/{github_app_id}/repositories`: Load all repositories for a specific GitHub app
  - `GET /github-apps/{github_app_id}/repositories/{owner}/{repo}/branches`: Load all branches for a specific repository
- Applied `IgnoreReadOnlyApiToken` middleware to all routes

This feature enables users to create GitHub apps, view repositories, and access repository branches.

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
This PR is the same as https://github.com/coollabsio/coolify/pull/3921 I think you have selected the worng branch.

**Comment by xmahbub** [comment]
Yes 🫥

**Comment by peaklabs-dev** [comment]
So both changes are now in one [PR](https://github.com/coollabsio/coolify/pull/3921) right?

**Comment by xmahbub** [comment]
I want to have to seperate PR

**Comment by xmahbub** [comment]
yes both are in one #3921 . Ok thank you

**Comment by xmahbub** [comment]
I have closed this PR  and change the title of the fist PR #3921 and also change the details comment. Is it OK now

**Comment by peaklabs-dev** [comment]
Perfect thanks

**Pull request closed without merging**
