### PR TITLE
[WIP] Reworked how remote commands work

### PR DESCRIPTION
**Pull request by Thijmen**
This is an attempt to rework some of the internals of Coolify to use a more OOP structured way on how remote commands are being executed.

Consider this heavily WIP, do _not_ merge yet.

# Status

Here's a status list of things that are done and need to do:

- [ ] Implement builds and start of:
  - [x]  Dockerfile
  - [x] Simple dockerfile (from the application itself)
  - [x] Docker Compose files
  - [x] Docker image
  - [ ] Static deployment
  - [ ] Pull Request deployments
 - [ ] Implement Restarts

### CODE REVIEW

**Comment by andrasbacsai** [comment]
I have checked a few files, and it looks very promising! Thank you!

**Comment by Thijmen** [comment]
Thanks @andrasbacsai, it's still WIP. I plan on making this an experimental feature so we can safely merge this in the future and opt-in on this.

Ofcourse I will be adding some integration tests as well and make them part of the GH Actions.

**Comment by Thijmen** [comment]
> #### ⚠️ GitGuardian has uncovered 1 secret following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secret in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.

@andrasbacsai you'll need to sign off on this secret in GitGuardian. It's the private key for the testing host.

**Comment by LEstradioto** [comment]
Hey I did a PR on your branch @Thijmen to closes Static deployment (appreciate a review!)
Now, I will work on Pull Request deployments

**Comment by andrasbacsai** [comment]
Too many things changed since this PR, so I have to close this one.

**Pull request closed without merging**
