### PR TITLE
Add PHP Codestyles

### PR DESCRIPTION
**Pull request by Thijmen**
I've added Laravel Pint to fix codestyle. Laravel Pint can be pretty opinionated, but seeing as Coolify heavily relies on Laravel, I think it could be a good fix.

Also good to note that it's my first time adding a GH Actions workflow to a repo that I do not own; please bear with me while I fix this PR until it's good to go :) 

I appreciate Coolify and hope to help out via this way! :)

### CODE REVIEW

**Review by victormicco — APPROVED** [review]
This refactor sounds great to me, it follows patterns and its not breaking any of them

**Comment by Thijmen** [comment]
Appreciate your words @victormicco, I am keen on helping the team out with improving the product and developer experience 😄

**Comment by andrasbacsai** [comment]
> Appreciate your words @victormicco, I am keen on helping the team out with improving the product and developer experience 😄

GJ3aj57WEAA25WK

**Comment by andrasbacsai** [comment]
> I've added Laravel Pint to fix codestyle. Laravel Pint can be pretty opinionated, but seeing as Coolify heavily relies on Laravel, I think it could be a good fix.
> 
> Also good to note that it's my first time adding a GH Actions workflow to a repo that I do not own; please bear with me while I fix this PR until it's good to go :)
> 
> I appreciate Coolify and hope to help out via this way! :)

Thank you very much!

**Pull request merged**
