### PR TITLE
Adding MindsDB - WIP

### PR DESCRIPTION
**Pull request by Skeyelab**
## Changes
- Adding [MindsDB](https://mindsdb.com)

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
@Skeyelab This is a service right so it is comparable to WordPress for example ofc for AI but it is not a Database like Redis or Postgres right?

**Comment by Skeyelab** [comment]
@peaklabs-dev - correct, this is more of a service.  It acts like a front end to a user's existing DB

**Comment by Skeyelab** [comment]
@peaklabs-dev the issue I am having with this template is, everytime it is restarted, all your previous work is erased.

**Comment by peaklabs-dev** [comment]
Maybe change the volume mount to a volume instead of a bind mount (should not make a difference in losing data though) maybe a volume mount is missing?

**Comment by Skeyelab** [comment]
@peaklabs-dev - I had to add a postgres instance to hold the config data.  However, I am a little unsure how to generate random user/pass for PG and use it in the connection string for the mindsDB instance.

I am looking at these docs: https://docs.mindsdb.com/setup/environment-vars#mindsdb-configuration-storage

**Comment by peaklabs-dev** [comment]
Thank you for the PR 💜. I will fix it and send you a link to the commit so you know it next time.

**Comment by peaklabs-dev** [comment]
I fixed it in this commit: https://github.com/coollabsio/coolify/pull/3878/commits/c087f22056ba5fa21c3d1b9e179f8024db4462aa some docs for magic envs: https://coolify.io/docs/knowledge-base/docker/compose#coolifys-magic-environment-variables

**Pull request merged**
