### PR TITLE
changed copypassword fields in databases

### PR DESCRIPTION
**Pull request by scshiv29-dev**
in reference to issue #907

### CODE REVIEW

**Comment by paulocoutinhox** [comment]
Thanks!

**Review by Rados51 — APPROVED** [review]

**Comment by scshiv29-dev** [comment]
also added commits for feature #917 
new updated ui
image

**Comment by scshiv29-dev** [comment]
@andrasbacsai

**Comment by andrasbacsai** [comment]
Thanks for the PR! 💜

**Pull request merged**
