### PR TITLE
feat: add rocketchat template

### LINKED ISSUE #2318: [Feature]: Rocket.Chat Template
### Description

I want a template for Rocket.Chat merged into this Coolify repo.
Suppose you can get a Rocket.Chat template is working and merged I consider that the bounty is complete.

### Minimal Reproduction (if possible, example repository)

n/a

### Exception or Error

_No response_

### Version

n/a

### PR DESCRIPTION
**Pull request by LEstradioto**
This PR adds a new template for RocketChat

Closes #2318 

/claim #2318

### CODE REVIEW

**Comment by LEstradioto** [comment]
sorry, didnt get why gitguardian was alerting, did the .json exclude mistakenkly

I guess GitGuardin is false positive on mongodb stuff?

https://github.com/GitGuardian/sample_secrets/blob/main/postgres_model.js

**Comment by LEstradioto** [comment]
image

I did a scan locally with Guardian, it seems multiple files in templates get caught in this right. So it seems false positive. this is the scan from the .yml

@andrasbacsai , do you need services-templates.json added/generated or should I un-commit from this PR?

**Comment by iamEvanYT** [comment]
@LEstradioto he usually generates it for you after he merge multiple service PRs. BTW, you should do `/claim #2318` so you get the bounty.

**Comment by DeVoresyah** [comment]
great job @LEstradioto , thanks for your work~!

**Comment by andrasbacsai** [comment]
Thank you, @LEstradioto for the PR!

Please remove the `service-templates.json`. I will generate it after the merge :)

GitGuardian looks like a false positive.

About the `bounty` claim, were you able to register to Algora after all?

**Comment by LEstradioto** [comment]
Done. Thanks for the responses!

Contacted Algora and got fast response, still awaiting but I guess it will be fine.

Sorry for commits confusion. This is my first professional PR ;)
I really like this project. I will try to contribute better!

**Comment by andrasbacsai** [comment]
> Done. Thanks for the responses!
> 
> Contacted Algora and got fast response, still awaiting but I guess it will be fine.
> 
> Sorry for commits confusion. This is my first professional PR ;) I really like this project. I will try to contribute better!

Thank you! :)

I not 100% sure how to pay you out through Algora (this is the first paid bounty), but I'm in touch with the found (Ioannis) on Discord, so you will be paid, no matter what. :)

**Pull request merged**
