### PR TITLE
Debloat UI by removing duplicated safety text

### PR DESCRIPTION
**Pull request by steff-mat**
Currently, the warning located in Settings/Configuration seems to contain the same text as located in Disable 2 Two Step Verification modal, but is bloading the UI with the strong red color and improper fitment.

Proposed solution is to remove it correctly, so text duplication is avoided and UI is kept simple,

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
Why would you want to remove the warning?

**Comment by steff-mat** [comment]
I feel like there's no real value added, and the red it's quite strong visually.
Capture

Otherwise, if removal it's out of scope, I'll push another PR to remove md:w-[40rem] so it uses less vertical space on bigger screens

**Comment by peaklabs-dev** [comment]
I think I will fix this by adding an accordion like this:
image
and expanded:
image

What do you think?

**Comment by steff-mat** [comment]
I love the idea. 
I don't know why I didn't considered this approach, but I think this will do the trick. 
[Maybe also add a rounded-sm to it and keep only w-full with px-4 py-2 to keep it slim?]

**Comment by peaklabs-dev** [comment]
Done:
image
Is this what you would be looking for?

**Comment by steff-mat** [comment]
Oh yes, definetly looks better.

I think you can cancel this PR [as was created into main instead of next by mistake]

Thank you

**Pull request closed without merging**
