### PR TITLE
feat: add Calcom template

### PR DESCRIPTION
**Pull request by FranckKe**
Add [Calcom](https://cal.com/) template

[Docker compose from their Github](https://github.com/calcom/docker/blob/main/docker-compose.yaml) 

Different logos available on [their website](https://design.cal.com/assets/logos), included in this pr the white text svg.

### CODE REVIEW

**Comment by FranckKe** [comment]
Some variables did not set up as I thought they would like `$SERVICE_BASE64_CALCOM_KEY`. I do not grasp all of the magic yet, looking for feedback if anyone is testing this.

**Comment by SamAmann** [comment]
I've managed to make the instance start with this compose.yaml:
```
version: '3.8'
services:
  calcom:
    image: 'calcom/cal.com:latest'
    environment:
      - 'DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DATABASE:-calcom}'
      - 'DATABASE_DIRECT_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DATABASE:-calcom}'
      - 'WEBAPP_URL=${SERVICE_FQDN_CALCOM}'
      - 'NEXTAUTH_URL=${SERVICE_FQDN_CALCOM_API_AUTH}'
      - 'NEXTAUTH_SECRET=${SERVICE_BASE64_32_SECRET}'
      - 'CALENDSO_ENCRYPTION_KEY=${SERVICE_BASE64_32_SECRET}'
      - 'NEXT_PUBLIC_WEBAPP_URL=${SERVICE_FQDN_CALCOM}'
      - 'NEXT_PUBLIC_API_V2_URL=${SERVICE_API_V2_URL}'
      - 'CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}'
      - 'EMAIL_SERVER_HOST=${SMTP_HOST}'
      - 'EMAIL_SERVER_PORT=${SMTP_PORT}'
      - 'EMAIL_SERVER_USER=${SMTP_USER}'
      - 'EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}'
      - 'EMAIL_FROM=${MAIL_FROM}'
    depends_on:
      postgres:
        condition: service_healthy
    command: "sh -c \"\n  npx prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma &&\n  npx prisma db seed --schema /calcom/packages/prisma/schema.prisma &&\n  npm run start\n\"\n"
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:3000'
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DATABASE:-calcom}'
    volumes:
      - 'calcom-postgresql-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${SERVICE_USER_POSTGRES} -d ${POSTGRES_DATABASE:-calcom}'
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  calcom-postgresql-data: null

```

However, this instance does not starts "as new", skipping the first user creation... 
I'm then unable to connect to it 😅

Anyone has tried something?

**Review by SamAmann — CHANGES_REQUESTED** [review]
Here is my working version:
```
version: '3.8'
services:
  calcom:
    image: 'calcom/cal.com:latest'
    environment:
      - 'DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DATABASE:-calcom}'
      - 'DATABASE_DIRECT_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DATABASE:-calcom}'
      - 'WEBAPP_URL=${SERVICE_FQDN_CALCOM}'
      - 'ALLOWED_HOSTNAMES=["${SERVICE_FQDN_CALCOM"]'
      - 'NEXTAUTH_URL=${SERVICE_FQDN_CALCOM_API_AUTH}'
      - 'NEXTAUTH_SECRET=${SERVICE_BASE64_32_SECRET}'
      - 'CALENDSO_ENCRYPTION_KEY=${SERVICE_BASE64_32_SECRET}'
      - 'NEXT_PUBLIC_WEBAPP_URL=${SERVICE_FQDN_CALCOM}'
      - 'NEXT_PUBLIC_API_V2_URL=${SERVICE_API_V2_URL}'
      - 'CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}'
      - 'EMAIL_SERVER_HOST=${SMTP_HOST}'
      - 'EMAIL_SERVER_PORT=${SMTP_PORT}'
      - 'EMAIL_SERVER_USER=${SMTP_USER}'
      - 'EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}'
      - 'EMAIL_FROM=${MAIL_FROM}'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:3000'
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DATABASE:-calcom}'
    volumes:
      - 'calcom-postgresql-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${SERVICE_USER_POSTGRES} -d ${POSTGRES_DATABASE:-calcom}'
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  calcom-postgresql-data: null

```

EDIT: Added the `ALLOWED_HOSTNAMES=["${SERVICE_FQDN_CALCOM"]` to allow apps to be added (tested with Calendar ICS, which is working as intended).

I'm still having some issues (something related to the auth, as I'm regularly getting redirected to the localhost:3000 instead of the next_auth_url.

**Comment by morpheus-sapiens-amans** [comment]
> Here is my working version:
> 
> ```
> version: '3.8'
> services:
>   calcom:
>     image: 'calcom/cal.com:latest'
>     environment:
>       - 'DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DATABASE:-calcom}'
>       - 'DATABASE_DIRECT_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DATABASE:-calcom}'
>       - 'ALLOWED_HOSTNAMES=["${SERVICE_FQDN_CALCOM}"]'
>       - 'NEXTAUTH_URL=${SERVICE_FQDN_CALCOM_API_AUTH}'
>       - 'NEXTAUTH_SECRET=${SERVICE_BASE64_32_SECRET}'
>       - 'CALENDSO_ENCRYPTION_KEY=${SERVICE_BASE64_32_SECRET}'
>       - 'NEXT_PUBLIC_WEBAPP_URL=${SERVICE_FQDN_CALCOM}'
>       - 'NEXT_PUBLIC_API_V2_URL=${SERVICE_API_V2_URL}'
>       - 'CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}'
>       - 'EMAIL_SERVER_HOST=${SMTP_HOST}'
>       - 'EMAIL_SERVER_PORT=${SMTP_PORT}'
>       - 'EMAIL_SERVER_USER=${SMTP_USER}'
>       - 'EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}'
>       - 'EMAIL_FROM=${MAIL_FROM}'
>     depends_on:
>       postgres:
>         condition: service_healthy
>     healthcheck:
>       test:
>         - CMD
>         - curl
>         - '-f'
>         - 'http://localhost:3000'
>       interval: 30s
>       timeout: 10s
>       retries: 5
>     restart: unless-stopped
>   postgres:
>     image: 'postgres:16-alpine'
>     environment:
>       - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
>       - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
>       - 'POSTGRES_DB=${POSTGRES_DATABASE:-calcom}'
>     volumes:
>       - 'calcom-postgresql-data:/var/lib/postgresql/data'
>     healthcheck:
>       test:
>         - CMD-SHELL
>         - 'pg_isready -U ${SERVICE_USER_POSTGRES} -d ${POSTGRES_DATABASE:-calcom}'
>       interval: 10s
>       timeout: 5s
>       retries: 5
>     restart: unless-stopped
> volumes:
>   calcom-postgresql-data: null
> ```
> 
> **EDIT:** Added the `ALLOWED_HOSTNAMES=["${SERVICE_FQDN_CALCOM"]` to allow apps to be added (tested with Calendar ICS, which is working as intended).
> 
> Removed `WEBAPP_URL` as deprecated and replaced by `NEXT_PUBLIC_WEBAPP_URL` wich is already present.
> 
> I'm still having some issues (something related to the auth, as I'm regularly getting redirected to the localhost:3000 instead of the next_auth_url).

I have tried to run calcom on coolify as well. Nor the compose.yml nor the .env-exemple are good to deploy via docker-compose on coolify. Actualy, your template got me the farthest. I see 2 green services, I click to access the link and for a fraction of a second, I can spot the logo and auth-initial login screen, but then the system turns black.

**Comment by peaklabs-dev** [comment]
There is another PR open https://github.com/coollabsio/coolify/pull/3503 maybe you guys can work it out together but both of your templates did not work properly in my testing so it would be great if you could fix it and let me know when it works, thanks so much.

**Comment by FranckKe** [comment]
Thank you for the different feedback, here is an updated version. Completed the onboarding, connected an ICS calendar and tested login/logout without additional configuration.
Please let me know in more details if you have any issues

**Comment by peaklabs-dev** [comment]
Thank you for the PR 💜. I will test it and fix it if necessary.

**Comment by DesmondLouis** [comment]
Hi @FranckKe  I might be late on my comment but could you consider an update to enable external database usage? As of my last test, this service depends on a PostgreSQL database that is created internally. What if I already have a PostgreSQL database I want to use? How can I configure it? 
Fyi @peaklabs-dev

**Comment by peaklabs-dev** [comment]
@DesmondLouis You can just remove the Postgres DB form the compose file and add the details of your external DB to the env variabels. Make sure you connect cal.com to the same network as your DB to make it work.

**Pull request merged**
