### PR TITLE
feat(translation): install svelte-i18n

### PR DESCRIPTION
**Pull request by restray**
# 👋 Hello world

This pull request is focused on add the internationalization for coolify! So non English peoples can use it freely (without a shitty Google Translate to be honest lol)

## ❔ Why ?

I add [sveltekit-i18n](https://github.com/sveltekit-i18n/lib/) to the pnpm Dev-dependencies and default user language.

So this would let SysA or beginners to help the project!

## How does it works?

When the user connect to the website, it detect the language from the [Request header](https://developer.mozilla.org/docs/Web/HTTP/Headers/Accept-Language) (by default: English) and store it in a cookies `lang`.

Then the [locales](./src/lib/locales/) are loaded in the client.

If a translation is not found for the user's language, it fall-backs to English.

## ✅ ToDo

 - [x] Remove hard-coded texts
 - [x] Translate French (for an example)
 - [x] Translate English (for fallback)
 - [x] Create guidelines for translations with i18n.

## ❔ It remains 1 thing to do!

I didn't do the `switch language` part because of 2 things:
 - I'm not a designer at all
 - How the user switch of language? (dropdown flag system using [flagpedia](https://flagpedia.net/download/api) or dropdown using languages)

If someone can do it? Otherwise I can do it but that will take a lot of time!

### CODE REVIEW

**Comment by restray** [comment]
As far as I tested out, anyone can pull my branch and test it from here!
I work on Contribution Guide for translations!

Please do not hesitate to comment over here to inform me of anything on i18n

**Comment by andrasbacsai** [comment]
Wow! Thank you! I can do the rest (UI + switch button)! Really appreciate it!! 💜

**Comment by vasani-arpit** [comment]
Is this same as #365 ?

**Comment by andrasbacsai** [comment]
Yeah, unfortunately, lots of things change since this PR and I cannot merge it, I need to create a new branch based on this! :)

**Pull request closed without merging**
