### PR TITLE
feat: Foundry Virtual Tabletop template

### PR DESCRIPTION
**Pull request by phenomen**
[Foundry Virtual Tabletop](https://foundryvtt.com/) is a self-hosted & modern roleplaying platform.

## Changes
- Added Foundry VTT template.
- Added Foundry VTT logo.

### CODE REVIEW

**Comment by phenomen** [comment]
@peaklabs-dev Added FQDN generator and tested it on a new project - all works well.

**Comment by peaklabs-dev** [comment]
I tested it and it does not seem to work, you can check the container logs to debug. Please also add secret generation for username and password via the magic environment variables.

**Comment by phenomen** [comment]
> I tested it and it does not seem to work, you can check the container logs to debug. Please also add secret generation for username and password via the magic environment variables.

Username and password cannot be generated. Users should enter their own Foundry account credentials. It will not install the server software without a valid account. I tested it and it works with either username/password OR presigned release URL provided.

**Comment by peaklabs-dev** [comment]
Ah I see, so license key, username and password are required and from Foundry itself. I will add it like that then, thanks.

**Pull request merged**
