### PR TITLE
fix: Gitea PR preview not working as intended

### LINKED ISSUE #2757: [Bug]: Preview deployment not checking out PR on Gitea repos
### Description

Title pretty much says it all. Repository import does not checkout the PR when the Git host is Gitea. It only clones the application's "main" branch. Funnily enough, it does show the correct commit it *should* be checked out at :)

I think I've tracked it down to `generateGitImportCommands` not actually generating the checkout command:

https://github.com/coollabsio/coolify/blob/e9158b7305bb9253fe75a0e76ef34af62f75199b/app/Models/Application.php#L710

(I'm using Forgejo instead of Gitea, but it should be equivalent - Forgejo is a drop-in replacement for Gitea)

<details>
<summary>Deployment log (click to expand)</summary>

```
[2024-Jul-06 21:07:41.312931] Starting pull request (#34) deployment of https://git.nolog.cz/NoLog.cz/public-web.git:master.
[2024-Jul-06 21:07:41.493376] Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:latest.
[2024-Jul-06 21:07:41.599641]                                     

[COMMAND] docker rm -f igg8coo
[OUTPUT]
Error response from daemon: No such container: igg8coo

[2024-Jul-06 21:07:41.735646]                                     

[COMMAND] docker run -d --network coolify --name igg8coo --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:latest
[OUTPUT]
314a0b5b50a92edd4e263a2ef78749c1ce2366ebbe7e1dfa34b374e074c9dfca

[2024-Jul-06 21:07:42.518874]                                     

[COMMAND] docker exec igg8coo bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git ls-remote https://git.nolog.cz/NoLog.cz/public-web.git pull/34/head'
[OUTPUT]
ffc042523c7b5a591b0c21f7d8f3bf42f6134f19	refs/pull/34/head

[2024-Jul-06 21:07:42.529074] ----------------------------------------
[2024-Jul-06 21:07:42.531085] Importing https://git.nolog.cz/NoLog.cz/public-web.git:master (commit sha HEAD) to /artifacts/igg8coo.
[2024-Jul-06 21:07:42.533277] Checking out tag pull/34/head.
[2024-Jul-06 21:07:42.711591]                                     

[COMMAND] docker exec igg8coo bash -c 'git clone -b "master" https://git.nolog.cz/NoLog.cz/public-web.git /artifacts/igg8coo'
[OUTPUT]
Cloning into '/artifacts/igg8coo'...

[2024-Jul-06 21:07:44.504950]                                     

[COMMAND] docker exec igg8coo bash -c 'cd /artifacts/igg8coo && git log -1 ffc042523c7b5a591b0c21f7d8f3bf42f6134f19 --pretty=%B'
[OUTPUT]
reorder services

[2024-Jul-06 21:07:44.709551] Generating nixpacks configuration with: nixpacks plan -f toml --build-cmd "hugo --destination dist" --install-cmd "apt-get install -y hugo" /artifacts/igg8coo
[2024-Jul-06 21:07:44.928131]                                     

...
```
</details>

### Minimal Reproduction (if possible, example repository)

1. Create an application with a Gitea repository as its source.
2. Set up the Gitea webhook && enable preview deployments
3. Create PR in the repo

### Exception or Error

N/A - deploy log in description

### Version

v4.0.0-beta.306

### PR DESCRIPTION
**Pull request by Xiloe**
fixes #2757 

Adds a check for the `$git_type` of `gitea` when running `generateGitImportCommands` so it checks out the PR instead of the 'main' branch.

### CODE REVIEW

**Comment by Xiloe** [comment]
Removed the redundant if statement that contained an error and added a logical OR to the Github check as it's working the same way on Gitea. (checked with the commands manually as well)

**Comment by Xiloe** [comment]
Ran it on the dev docker compose, I can confirm that it works as expected,
image

**Comment by Xiloe** [comment]
@andrasbacsai could this be part of #2789 by any chance?

**Comment by andrasbacsai** [comment]
Thank you for the PR! It looks good!

**Pull request merged**
