### PR TITLE
feat: add jitsi template

### PR DESCRIPTION
**Pull request by LEstradioto**
/claim #2304

Changing proxy settings is needed to enable Jitsi share screen with more than 2 people, more instructions at [2304](https://github.com/coollabsio/coolify/issues/2304#issuecomment-2146748401)

Where we put this observation though?

### CODE REVIEW

**Comment by DeVoresyah** [comment]
hi @andrasbacsai , can you review this?

**Comment by DeVoresyah** [comment]
hi @andrasbacsai , can this one merged in the next release?

**Comment by kingRayhan** [comment]
+1 for this PR 👏

**Comment by LEstradioto** [comment]
Hey @peaklabs-dev !
1. Ive installed Jitsi just now (to test it) and the guidelines are right. We only need that two lines
2. About envs, Ive pushed a new commit

**Comment by peaklabs-dev** [comment]
Thank you for the PR 💜. I will test it and fix it if necessary.

**Pull request merged**
