### PR TITLE
Service: Flowise

### PR DESCRIPTION
**Pull request by rennokki**
## Changes
- Added new service: [Flowise](https://flowiseai.com)

## Issues
N/A

### CODE REVIEW

**Comment by rennokki** [comment]
@andrasbacsai

**Comment by peaklabs-dev** [comment]
Thank you for the PR 💜. I will test it and fix it if necessary.

**Comment by tomilagom** [comment]
Hi! I don't see Flowise as an available service after upgrading the coolify version. Does anyone see it?

image

**Comment by peaklabs-dev** [comment]
It will be available soon via this PR https://github.com/coollabsio/coolify/pull/3838

**Pull request merged**
