### PR TITLE
ui: Fixed z-index for version link.

### PR DESCRIPTION
**Pull request by chz**
Fixed z-index for version link.

### CODE REVIEW

**Comment by andrasbacsai** [comment]
> Fixed z-index for version link.

Thank you!!

**Comment by chz** [comment]
I can contribute with ui fixs if you have list of issues about ui. Or you can assign me. I'd love to help and contribute to coolify

**Comment by andrasbacsai** [comment]
> I can contribute with ui fixs if you have list of issues about ui. Or you can assign me. I'd love to help and contribute to coolify

Oh wow. Thank you! :) I will definitely need help with the UI part. I will make a few issues.

**Comment by chz** [comment]
Assign me i will help you.

**Pull request merged**
