### PR TITLE
Allow setting the contact and docs url with env variables.

### PR DESCRIPTION
**Pull request by hareland**
Simply allows setting the contact and docs url with env variables.

### CODE REVIEW

**Comment by andrasbacsai** [comment]
Thank you for the PR!

Why do you need this? This is a step to white-labeling.

**Comment by hareland** [comment]
Thanks for your reply. This is mainly because i run this internally in a volunteer organization, and a lot of people who logs in gets confused if they are looking for help. I could keep a fork for this but figured other people might also encounter this issue.

**Comment by hareland** [comment]
@andrasbacsai It might be better to add a optional "help" button on the sidebar instead with a admin setting tho - what do you think would be a better approach?

**Comment by peaklabs-dev** [comment]
For now this will not be added, we may add more white labeling feature in the future but not right now.

**Pull request closed without merging**
