### PR TITLE
refactor: Update search input placeholder in resource index view

### PR DESCRIPTION
**Pull request by nfnot**
## Issues
- fix : search input placeholder in resource index view

### CODE REVIEW

**Comment by andrasbacsai** [comment]
Why is this necessary?

**Comment by thereis** [comment]
@andrasbacsai The autofocus is driving me nuts, it's always autocompleting with my personal email that I use to login in the platform... and since this triggers the automatic filter, it doesn't display any of services because there are no services matching my personal email...

**Comment by liberocks** [comment]
In my case, when selecting a resource the search input is autofocused and autofilled that makes no resource appears. It's very annoying.

**Comment by pahenn** [comment]
Or adding `autocomplete="off"` could also be a fix here. That was you could start typing immediately if you really wanted, but it won't fill in our email addresses

**Comment by andrasbacsai** [comment]
Are you on the latest released version (347)?

**Comment by andrasbacsai** [comment]
I am asking, because on the latest version, every input box got the `autocomplete="off"` by default, and only a few specific (username/password) has it.

**Comment by thereis** [comment]
Yes @andrasbacsai, I'm using the cloud version with the version 347

image

**Comment by nfnot** [comment]
The autofocus is really frustrating. It keeps autofilling my email, which I use to log in, This triggers the automatic filter and shows no services because none of them match my email.

**Comment by pahenn** [comment]
I am on 347, and see that autocomplete is set to off... I wouldn't have thought I would be getting the behavior I'm getting, but I'm hoping it's the autofocus, and that merging this fixed it

**Comment by andrasbacsai** [comment]
Okay, I will set autofocus off as well. It will be released tomorrow morning.

**Comment by moshetanzer** [comment]
This is not enough. It should have a name autocapitalise off autocorrect off and autofill off and possibly even a type search to cover all cases. This has made coolify unusable.

**Comment by andrasbacsai** [comment]
Can you please check if it is better with v349? I cannot reproduce the issue.

**Comment by andrasbacsai** [comment]
> This is not enough. It should have a name autocapitalise off autocorrect off and autofill off and possibly even a type search to cover all cases. This has made coolify unusable.

What are those autocapitalise, autofill off options? Input boxes does not have such thing as I know - but maybe I am wrong.

**Comment by thereis** [comment]
@andrasbacsai the problem was fixed, thank you!

**Comment by moshetanzer** [comment]
> > This is not enough. It should have a name autocapitalise off autocorrect off and autofill off and possibly even a type search to cover all cases. This has made coolify unusable.
> 
> 
> 
> What are those autocapitalise, autofill off options? Input boxes does not have such thing as I know - but maybe I am wrong.

They are more valid html attributes that basically just tell chrome to leave this field alone 😂. Not fixed on my side.

**Comment by pahenn** [comment]
@andrasbacsai still not fixed for me, upgraded to 349. [Here is a Loom](https://www.loom.com/share/c7f4cfe91a2149cea165ae66494df4ec?sid=ec20d099-d136-4408-842e-176a2622b550). 

I'll see if I can fix it on my machine where it's definitely happening and submit a PR

**Comment by moshetanzer** [comment]
@andrasbacsai also here still brken on 349. 

here is a succesful example of how to mitigate autocomplete

```
<input class="native-input sc-ion-input-md" aria-labelledby="ion-input-0-lbl" autocapitalize="off" autocomplete="off" autocorrect="off" name="pf.username" placeholder="" required="" spellcheck="false" type="text">
```
it needs a name attribute, set as text and autocapitlize etc.. - please try this

**Comment by pahenn** [comment]
On 355, and no longer a problem! Thank you!

**Pull request merged**
