### PR TITLE
Added Penpot service

### PR DESCRIPTION
**Pull request by hades200082**
Added a working Penpot compose file based on instructions from https://help.penpot.app/technical-guide/getting-started/#configure-penpot-with-docker

Added some default env vars too.

### CODE REVIEW

**Comment by compgeniuses** [comment]
this is a wonderful addiditon, cant wait for penpot v2.0 to release

**Comment by miguelgargallo** [comment]
This would be amzing

**Comment by andrasbacsai** [comment]
Thank you! I will test it out and release as soon as it is ready!

**Comment by miguelgargallo** [comment]
thanks :)

**Pull request merged**
