### PR TITLE
Add dynamic traefik config volume

### PR DESCRIPTION
**Pull request by snimshchikov**
Can be used to make adjustments to traefik dynamic config
As suggested in #779

### CODE REVIEW

**Comment by floco** [comment]
Hello,
Just what I need too to publish services not managed by coolify.
Anyone knows if there is a plan to merge this ? or an alternative ?
Thanks

**Comment by snimshchikov** [comment]
> Hello, Just what I need too to publish services not managed by coolify. Anyone knows if there is a plan to merge this ? or an alternative ? Thanks

I don't think that this is mergable. I opened it to make a statement that it is needed. If you want to replicate what I do here, you can replace traefik container with something like this (you need to stop the original before starting a new one, coolify will recreate the original in about one minute if no traefik is running)
```
docker run --restart always --add-host 'host.docker.internal:host-gateway' --add-host 'host.docker.internal:172.16.0.1' -v coolify-traefik-letsencrypt:/etc/traefik/acme -v ~/coolify-traefik-dynamic-config:/etc/traefik/dynamic  -v /var/run/docker.sock:/var/run/docker.sock  --network coolify-infra  -p "80:80"  -p "443:443"  --name coolify-proxy  -d traefik-secure --providers.file.directory=/etc/traefik/dynamic/ --providers.file.watch=true
```

You can now place your config in `~/coolify-traefik-dynamic-config`

**Comment by floco** [comment]
Many thanks @snimshchikov :-)
I will try this.

**Comment by andrasbacsai** [comment]
Thanks for the PR. 💜️  
I would like to concentrate on v4. That is why I do not plan to add more features to v3.

This feature is available in v4 btw.

**Pull request closed without merging**
