### PR TITLE
Update supabase add supavisor

### PR DESCRIPTION
**Pull request by djsisson**
Please Note this is a breaking change for existing templates, due to moving logs out of main database.
This template now has the supavisor builtin and matches the current version found for self hosted supabase

due to init scripts not running for existing databases, you can simply run the 2 new and 1 altered sql file before implementing:

create the _supavisor db, create 2 schemas for logs and supavisor

the template will then work as expected

## Changes
- 
updated versions for most images
added supavisor
move logs out of main database

## Issues
- fix #
https://github.com/coollabsio/coolify/pull/2712

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
Thanks for the PR 💜. And don't worry about the breaking change, service templates are not synced with existing deployments, so only new templates will be affected by your change.

**Comment by Geczy** [comment]
amazing! ty

**Comment by rajaiswal** [comment]
@peaklabs-dev This is great work, thank you! I have a self-hosted supabase already running in prod, could you please elaborate on these instructions you mentioned to incorporate the new docker-compose file in the existing stack:
```
due to init scripts not running for existing databases, you can simply run the 2 new and 1 altered sql file before implementing:

create the _supavisor db, create 2 schemas for logs and supavisor
```
Can you explicitly point out which 2 new and 1 altered sql file need to be run? In my case, if I update the my current docker compose file with this new one, and then run the sql commands, and then restart th containers, should it just work?

**Comment by peaklabs-dev** [comment]
If you use the new updated template and start it, everything should just work without manual intervention (I am not too familiar with Supabase itself though).

**Comment by djsisson** [comment]
@rajaiswal the updated sql files refer to creating the database _supabase and the 2 schemas inside (supavisor and analytics)

if you do not want this you can contine to just use your existing compose and just paste in the supavisor section, but you will need to alter it to point to your current postgres database not the _supabase database to store the tenants.

Please note you would still need to create a schema for supavisor in order for it to work

**Comment by rajaiswal** [comment]
@djsisson As per your recommendation, I replaced '_supabase' with 'postgres' and created a schema for supavisor and copied the supavisor section, and all services are now up and running green. I can even access the supabase dashboard. But I am unable to connect to the db directly or supavisor via the postgres protocol. I tried:
`postgresql://<username>:<password>@<host ip>:6543/postgres` and also tried `4000`, `6432` and `5432` but I keep getting connection refused. I ensured the server firewall is set up to receive connections on all these ports. Am I missing a step? ChatGPT says I need to do:
```
supabase-supavisor:
  # ... other configurations ...
  ports:
    - "6543:4000"
 ```
 or am I missing something in my caddy config?

**Comment by djsisson** [comment]
@rajaiswal assuming you are in same docker network then it would be something like this:

postgresql://postgres.dev_tenant:postgrespassword@supabase-supavisor:6543/postgres?pgbouncer=true

if you are currently connecting via public port mapping, then you would need to add one to compose for supavisor too

the .dev_tenant refers to the tenant name (its default is dev_tenant in compose)

you can also check in your supabase dashboard, switch to _supavisor schema and view tables

**Comment by rajaiswal** [comment]
@djsisson Perfect, that worked. Thanks so much!

**Comment by Geczy** [comment]
Am I doing `dev_tenant` correctly? This was my old connection string, which worked with my previous implementation of Supavisor, but broke on this implementation. 

Should I instead be passing it through the username as well? I can try

The error I'm noticing is in Sentry, `Invalid `prisma.user.findFirst()` invocation: Error querying the database: FATAL: Max client connections reached`

```
/postgres?pgbouncer=true&connection_limit=1&options=reference%3Ddev_tenant&sslmode=disable
```

**Comment by Geczy** [comment]
Also, I don't see the supavisor schema. Could this be why it's acting as if it's not working?

CleanShot 2024-10-16 at 07 56 02@2x

**Comment by djsisson** [comment]
@Geczy your connection string is also valid method, if you are using the new template, the supavisor schema is in the other database with the logs.

but the error you are getting would be to do with no supavisor if it wasnt working, (you can also check supavisor logs)

is this prod mode or in dev?

**Comment by Geczy** [comment]
The error is in prod, and my supabase instance is "prod" too, not sure if that's a selection I needed to make?

this does show up in the logs page

CleanShot 2024-10-16 at 08 07 36@2x

but returns no results 

CleanShot 2024-10-16 at 08 07 26@2x

**Comment by Geczy** [comment]
This is a completely new coolify supabase setup, using the template from a few days ago on next branch https://github.com/coollabsio/coolify/blob/next/templates/compose/supabase.yaml

I copy pasted this template into a coolify docker compose project since I wanted to modify it to add some exposed ports, and pg_audit logging in the db startup config

**Comment by djsisson** [comment]
in the logs in coolify what do u see in supavisor

**Comment by Geczy** [comment]
here's the diff of my template

https://github.com/coollabsio/coolify/compare/next...Geczy:coolify:patch-7

```json
2024-10-16T13:06:55.298004126Z 13:06:55.295 request_id=F_7wwDZ6hoCVN_MABjvh region=local [info] GET /api/health
2024-10-16T13:06:55.298064886Z 13:06:55.295 request_id=F_7wwDZ6hoCVN_MABjvh region=local [info] Sent 204 in 166µs
2024-10-16T13:07:00.382003923Z 13:07:00.381 request_id=F_7wwWWmcrlvEXYABjwB region=local [info] GET /api/health
2024-10-16T13:07:00.382386205Z 13:07:00.382 request_id=F_7wwWWmcrlvEXYABjwB region=local [info] Sent 204 in 392µs
2024-10-16T13:07:05.450954967Z 13:07:05.449 request_id=F_7wwpO1qoY4vSAABjwh region=local [info] GET /api/health
2024-10-16T13:07:05.451013567Z 13:07:05.449 request_id=F_7wwpO1qoY4vSAABjwh region=local [info] Sent 204 in 144µs
2024-10-16T13:07:10.558281774Z 13:07:10.556 request_id=F_7ww8Qgp4UyXKIABAOC region=local [info] GET /api/health
2024-10-16T13:07:10.558891617Z 13:07:10.557 request_id=F_7ww8Qgp4UyXKIABAOC region=local [info] Sent 204 in 873µs
2024-10-16T13:07:15.626867944Z 13:07:15.625 request_id=F_7wxPJE66qyPHwABAOi region=local [info] GET /api/health
2024-10-16T13:07:15.628472272Z 13:07:15.626 request_id=F_7wxPJE66qyPHwABAOi region=local [info] Sent 204 in 338µs
2024-10-16T13:07:20.712309606Z 13:07:20.711 request_id=F_7wxiFcvEbZ-_IABAPC region=local [info] GET /api/health
2024-10-16T13:07:20.712903009Z 13:07:20.711 request_id=F_7wxiFcvEbZ-_IABAPC region=local [info] Sent 204 in 556µs
2024-10-16T13:07:25.793724811Z 13:07:25.793 request_id=F_7wx1BO_vHHFnwAAthj region=local [info] GET /api/health
2024-10-16T13:07:25.794546855Z 13:07:25.793 request_id=F_7wx1BO_vHHFnwAAthj region=local [info] Sent 204 in 272µs
2024-10-16T13:07:30.871238159Z 13:07:30.870 request_id=F_7wyH7tHVuZ2-AABjxB region=local [info] GET /api/health
2024-10-16T13:07:30.871380080Z 13:07:30.870 request_id=F_7wyH7tHVuZ2-AABjxB region=local [info] Sent 204 in 340µs
2024-10-16T13:07:35.956335871Z 13:07:35.955 request_id=F_7wya4H8bzpdPQABjxh region=local [info] GET /api/health
2024-10-16T13:07:35.957941200Z 13:07:35.956 request_id=F_7wya4H8bzpdPQABjxh region=local [info] Sent 204 in 299µs
2024-10-16T13:07:41.053389090Z 13:07:41.052 request_id=F_7wyt3PSzRaKCMABjyB region=local [info] GET /api/health
2024-10-16T13:07:41.054331255Z 13:07:41.053 request_id=F_7wyt3PSzRaKCMABjyB region=local [info] Sent 204 in 1ms
2024-10-16T13:07:46.153552768Z 13:07:46.150 request_id=F_7wzA2zubp6BvwABjyh region=local [info] GET /api/health
2024-10-16T13:07:46.153611769Z 13:07:46.153 request_id=F_7wzA2zubp6BvwABjyh region=local [info] Sent 204 in 2ms
2024-10-16T13:07:51.255725061Z 13:07:51.254 request_id=F_7wzT3h4DzR01MABjzB region=local [info] GET /api/health
2024-10-16T13:07:51.255777101Z 13:07:51.254 request_id=F_7wzT3h4DzR01MABjzB region=local [info] Sent 204 in 144µs
2024-10-16T13:07:51.512465316Z 13:07:51.509 project=dev_tenant user=postgres region=local mode=transaction type=single [warning] ClientHandler: socket closed with reason {:shutdown, :socket_closed}
2024-10-16T13:07:51.512526477Z 13:07:51.509 project=dev_tenant user=postgres region=local mode=transaction type=single [warning] ClientHandler: socket closed with reason {:shutdown, :socket_closed}
2024-10-16T13:07:51.617627383Z 13:07:51.612 project=dev_tenant user=postgres region=local mode=transaction type=single [warning] ClientHandler: socket closed with reason {:shutdown, :socket_closed}
2024-10-16T13:07:56.342900320Z 13:07:56.342 request_id=F_7wzm0jMEpAYvwABjzh region=local [info] GET /api/health
2024-10-16T13:07:56.342956960Z 13:07:56.342 request_id=F_7wzm0jMEpAYvwABjzh region=local [info] Sent 204 in 165µs
2024-10-16T13:08:01.444650418Z 13:08:01.442 request_id=F_7wz50l-ObGhMwABj0B region=local [info] GET /api/health
2024-10-16T13:08:01.444712099Z 13:08:01.442 request_id=F_7wz50l-ObGhMwABj0B region=local [info] Sent 204 in 157µs
2024-10-16T13:08:06.535372583Z 13:08:06.530 request_id=F_7w0MxvqQ7TtH8AAtiD region=local [info] GET /api/health
2024-10-16T13:08:06.535422263Z 13:08:06.531 request_id=F_7w0MxvqQ7TtH8AAtiD region=local [info] Sent 204 in 553µs
2024-10-16T13:08:11.642122275Z 13:08:11.641 request_id=F_7w0f0R2RiZEEAAAtij region=local [info] GET /api/health
2024-10-16T13:08:11.642283996Z 13:08:11.641 request_id=F_7w0f0R2RiZEEAAAtij region=local [info] Sent 204 in 139µs
2024-10-16T13:08:16.726108093Z 13:08:16.725 request_id=F_7w0ywW_MG0jmIABj0h region=local [info] GET /api/health
2024-10-16T13:08:16.726169773Z 13:08:16.725 request_id=F_7w0ywW_MG0jmIABj0h region=local [info] Sent 204 in 136µs
2024-10-16T13:08:21.837448496Z 13:08:21.836 request_id=F_7w1Fy_V5QE6rIABj1B region=local [info] GET /api/health
2024-10-16T13:08:21.837507336Z 13:08:21.836 request_id=F_7w1Fy_V5QE6rIABj1B region=local [info] Sent 204 in 141µs
2024-10-16T13:08:26.910824986Z 13:08:26.907 request_id=F_7w1Yr33q41h_AABj1h region=local [info] GET /api/health
2024-10-16T13:08:26.910886466Z 13:08:26.907 request_id=F_7w1Yr33q41h_AABj1h region=local [info] Sent 204 in 181µs
2024-10-16T13:08:31.994902134Z 13:08:31.994 request_id=F_7w1rohk9ZEgqgABj2B region=local [info] GET /api/health
2024-10-16T13:08:31.996199101Z 13:08:31.994 request_id=F_7w1rohk9ZEgqgABj2B region=local [info] Sent 204 in 1ms
2024-10-16T13:08:37.079817411Z 13:08:37.079 request_id=F_7w1-lFa5jyUx8ABj2h region=local [info] GET /api/health
2024-10-16T13:08:37.079858331Z 13:08:37.079 request_id=F_7w1-lFa5jyUx8ABj2h region=local [info] Sent 204 in 186µs
2024-10-16T13:08:42.134604295Z 13:08:42.134 request_id=F_7w2RaQcDtTthYABj3B region=local [info] GET /api/health
2024-10-16T13:08:42.134823296Z 13:08:42.134 request_id=F_7w2RaQcDtTthYABj3B region=local [info] Sent 204 in 142µs
2024-10-16T13:08:47.215362757Z 13:08:47.214 request_id=F_7w2kVlrFEJRvwABj3h region=local [info] GET /api/health
2024-10-16T13:08:47.215422757Z 13:08:47.214 request_id=F_7w2kVlrFEJRvwABj3h region=local [info] Sent 204 in 142µs
2024-10-16T13:08:52.291694919Z 13:08:52.290 request_id=F_7w23PyQbpRFlYABj4B region=local [info] GET /api/health
2024-10-16T13:08:52.291743600Z 13:08:52.290 request_id=F_7w23PyQbpRFlYABj4B region=local [info] Sent 204 in 159µs
2024-10-16T13:08:57.369174531Z 13:08:57.368 request_id=F_7w3KKX7xZPLeYABj4h region=local [info] GET /api/health
2024-10-16T13:08:57.369234812Z 13:08:57.368 request_id=F_7w3KKX7xZPLeYABj4h region=local [info] Sent 204 in 163µs
2024-10-16T13:09:02.490257174Z 13:09:02.488 request_id=F_7w3dPJXZ0zCZwAAtjD region=local [info] GET /api/health
2024-10-16T13:09:02.490309214Z 13:09:02.488 request_id=F_7w3dPJXZ0zCZwAAtjD region=local [info] Sent 204 in 141µs
2024-10-16T13:09:07.602589574Z 13:09:07.601 request_id=F_7w3wSMC4ENgQIABj5B region=local [info] GET /api/health
2024-10-16T13:09:07.602629974Z 13:09:07.601 request_id=F_7w3wSMC4ENgQIABj5B region=local [info] Sent 204 in 142µs
2024-10-16T13:09:12.716163905Z 13:09:12.715 request_id=F_7w4DVeQ2WWNaYABj5h region=local [info] GET /api/health
2024-10-16T13:09:12.716216745Z 13:09:12.715 request_id=F_7w4DVeQ2WWNaYABj5h region=local [info] Sent 204 in 161µs
2024-10-16T13:09:17.800684527Z 13:09:17.798 request_id=F_7w4WRXrzSwTSMABj6B region=local [info] GET /api/health
2024-10-16T13:09:17.800727607Z 13:09:17.798 request_id=F_7w4WRXrzSwTSMABj6B region=local [info] Sent 204 in 136µs
2024-10-16T13:09:22.878478477Z 13:09:22.877 request_id=F_7w4pMSRSjx5wEABj6h region=local [info] GET /api/health
2024-10-16T13:09:22.878510957Z 13:09:22.877 request_id=F_7w4pMSRSjx5wEABj6h region=local [info] Sent 204 in 146µs
2024-10-16T13:09:27.945266413Z 13:09:27.944 request_id=F_7w48EYz6J7B34ABj7B region=local [info] GET /api/health
2024-10-16T13:09:27.945319454Z 13:09:27.944 request_id=F_7w48EYz6J7B34ABj7B region=local [info] Sent 204 in 148µs
2024-10-16T13:09:33.026841790Z 13:09:33.026 request_id=F_7w5O_6uzMTv8IABj7h region=local [info] GET /api/health
2024-10-16T13:09:33.028896521Z 13:09:33.026 request_id=F_7w5O_6uzMTv8IABj7h region=local [info] Sent 204 in 218µs
2024-10-16T13:09:38.092764368Z 13:09:38.092 request_id=F_7w5h3tpFx15AMABj8B region=local [info] GET /api/health
2024-10-16T13:09:38.095296461Z 13:09:38.092 request_id=F_7w5h3tpFx15AMABj8B region=local [info] Sent 204 in 188µs
2024-10-16T13:09:43.170986213Z 13:09:43.170 request_id=F_7w50ycLsHBP74ABj8h region=local [info] GET /api/health
2024-10-16T13:09:43.173506626Z 13:09:43.170 request_id=F_7w50ycLsHBP74ABj8h region=local [info] Sent 204 in 148µs
2024-10-16T13:09:48.263360536Z 13:09:48.261 request_id=F_7w6HwOP6Sp_ywABj9B region=local [info] GET /api/health
2024-10-16T13:09:48.267148955Z 13:09:48.262 request_id=F_7w6HwOP6Sp_ywABj9B region=local [info] Sent 204 in 1ms
2024-10-16T13:09:53.370270817Z 13:09:53.369 request_id=F_7w6ax8KYmf4mAABj9h region=local [info] GET /api/health
2024-10-16T13:09:53.374560599Z 13:09:53.369 request_id=F_7w6ax8KYmf4mAABj9h region=local [info] Sent 204 in 681µs
2024-10-16T13:09:58.454685544Z 13:09:58.453 request_id=F_7w6tuFfc7LXsoABj-B region=local [info] GET /api/health
2024-10-16T13:09:58.459354128Z 13:09:58.454 request_id=F_7w6tuFfc7LXsoABj-B region=local [info] Sent 204 in 1ms
2024-10-16T13:10:03.564934328Z 13:10:03.563 request_id=F_7w7AwkbImmcCkABj-h region=local [info] GET /api/health
2024-10-16T13:10:03.565959054Z 13:10:03.564 request_id=F_7w7AwkbImmcCkABj-h region=local [info] Sent 204 in 758µs
2024-10-16T13:10:08.654893490Z 13:10:08.653 request_id=F_7w7TuBCAHsyBkABj_B region=local [info] GET /api/health
2024-10-16T13:10:08.654942491Z 13:10:08.653 request_id=F_7w7TuBCAHsyBkABj_B region=local [info] Sent 204 in 514µs
2024-10-16T13:10:13.739499067Z 13:10:13.737 request_id=F_7w7mp_vlQIh-sABj_h region=local [info] GET /api/health
2024-10-16T13:10:13.741150396Z 13:10:13.737 request_id=F_7w7mp_vlQIh-sABj_h region=local [info] Sent 204 in 1ms
2024-10-16T13:10:18.813729193Z 13:10:18.813 request_id=F_7w75kPaVMOyWkABkAB region=local [info] GET /api/health
2024-10-16T13:10:18.813770313Z 13:10:18.813 request_id=F_7w75kPaVMOyWkABkAB region=local [info] Sent 204 in 147µs
2024-10-16T13:10:23.892502905Z 13:10:23.891 request_id=F_7w8MfMrxWzkTYABkAh region=local [info] GET /api/health
2024-10-16T13:10:23.894838637Z 13:10:23.892 request_id=F_7w8MfMrxWzkTYABkAh region=local [info] Sent 204 in 349µs
2024-10-16T13:10:28.981319113Z 13:10:28.979 request_id=F_7w8fb7fqG51k4AAtjj region=local [info] GET /api/health
2024-10-16T13:10:28.986599940Z 13:10:28.982 request_id=F_7w8fb7fqG51k4AAtjj region=local [info] Sent 204 in 4ms
2024-10-16T13:10:34.075488471Z 13:10:34.072 request_id=F_7w8yaguYDHvvwAAtkD region=local [info] GET /api/health
2024-10-16T13:10:34.075553232Z 13:10:34.073 request_id=F_7w8yaguYDHvvwAAtkD region=local [info] Sent 204 in 591µs
2024-10-16T13:10:39.169114230Z 13:10:39.159 request_id=F_7w9FXMfEld5c0ABkBB region=local [info] GET /api/health
2024-10-16T13:10:39.169174510Z 13:10:39.160 request_id=F_7w9FXMfEld5c0ABkBB region=local [info] Sent 204 in 1ms
2024-10-16T13:10:44.228138290Z 13:10:44.226 request_id=F_7w9YPRZjcACIwABkBh region=local [info] GET /api/health
2024-10-16T13:10:44.228218411Z 13:10:44.226 request_id=F_7w9YPRZjcACIwABkBh region=local [info] Sent 204 in 662µs
2024-10-16T13:10:49.300851705Z 13:10:49.298 request_id=F_7w9rIhq4JfficABkCB region=local [info] GET /api/health
2024-10-16T13:10:49.301710510Z 13:10:49.298 request_id=F_7w9rIhq4JfficABkCB region=local [info] Sent 204 in 725µs
2024-10-16T13:10:54.395391077Z 13:10:54.393 request_id=F_7w9-HXuGKY5YkABkCh region=local [info] GET /api/health
2024-10-16T13:10:54.395444957Z 13:10:54.394 request_id=F_7w9-HXuGKY5YkABkCh region=local [info] Sent 204 in 592µs
2024-10-16T13:10:57.260107522Z 13:10:57.259 project=dev_tenant user=postgres region=local mode=transaction type=single [warning] ClientHandler: socket closed with reason {:shutdown, :terminate_received}
```

**Comment by Geczy** [comment]
Supabase rest logs show this, but only 2 instances of this error

```js
2024-10-16T12:00:28.925153638Z 16/Oct/2024:12:00:28 +0000: {"code":"PGRST003","details":null,"hint":null,"message":"Timed out acquiring connection from connection pool."}
```

See a bunch of these in supabase vector logs

```js
2024-10-16T11:22:14.316452011Z 2024-10-16T11:22:14.316351Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] has been rate limited 5 times.
2024-10-16T11:22:14.316802733Z 2024-10-16T11:22:14.316427Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"upcase\" at (475:515): expected string, got null" error_type="conversion_failed" stage="processing" internal_log_rate_limit=true
2024-10-16T11:22:14.321603438Z 2024-10-16T11:22:14.320955Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] is being rate limited.
2024-10-16T11:28:42.707150074Z 2024-10-16T11:28:42.706789Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] has been rate limited 1 times.
2024-10-16T11:28:42.707629876Z 2024-10-16T11:28:42.706980Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"upcase\" at (475:515): expected string, got null" error_type="conversion_failed" stage="processing" internal_log_rate_limit=true
2024-10-16T11:28:42.707651716Z 2024-10-16T11:28:42.707503Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] is being rate limited.
2024-10-16T11:43:29.967137110Z 2024-10-16T11:43:29.966391Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] has been rate limited 1 times.
2024-10-16T11:43:29.967438992Z 2024-10-16T11:43:29.966412Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"upcase\" at (475:515): expected string, got null" error_type="conversion_failed" stage="processing" internal_log_rate_limit=true
2024-10-16T11:43:29.967451992Z 2024-10-16T11:43:29.966843Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] is being rate limited.
2024-10-16T11:46:04.926451510Z 2024-10-16T11:46:04.926135Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] has been rate limited 3 times.
2024-10-16T11:46:04.927564556Z 2024-10-16T11:46:04.926402Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"upcase\" at (475:515): expected string, got null" error_type="conversion_failed" stage="processing" internal_log_rate_limit=true
2024-10-16T11:46:04.927707196Z 2024-10-16T11:46:04.927668Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] is being rate limited.
2024-10-16T12:00:02.006962008Z 2024-10-16T12:00:02.000787Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Stopped watching for container logs. container_id=b411e8f5915e15bbc7c6d1abb5c99ac1f30270a64713dee411cd78da8adf3fe0
2024-10-16T12:00:02.007032688Z 2024-10-16T12:00:02.004285Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Started watching for container logs. container_id=b411e8f5915e15bbc7c6d1abb5c99ac1f30270a64713dee411cd78da8adf3fe0
2024-10-16T12:00:02.398299137Z 2024-10-16T12:00:02.371140Z ERROR source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Internal log [Received out of order log message.] has been rate limited 52 times.
2024-10-16T12:00:02.399444303Z 2024-10-16T12:00:02.371165Z ERROR source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Received out of order log message. error_type="condition_failed" stage="receiving" container_id="b411e8f5915e15bbc7c6d1abb5c99ac1f30270a64713dee411cd78da8adf3fe0" timestamp="2024-10-16T12:00:01.812259168Z" internal_log_rate_limit=true
2024-10-16T12:00:02.400202747Z 2024-10-16T12:00:02.371815Z ERROR source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Internal log [Received out of order log message.] is being rate limited.
2024-10-16T12:00:02.401514154Z 2024-10-16T12:00:02.371967Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Stopped watching for container logs. container_id=b411e8f5915e15bbc7c6d1abb5c99ac1f30270a64713dee411cd78da8adf3fe0
2024-10-16T12:00:03.087983460Z 2024-10-16T12:00:03.086891Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Started watching for container logs. container_id=b411e8f5915e15bbc7c6d1abb5c99ac1f30270a64713dee411cd78da8adf3fe0
2024-10-16T12:00:12.148823598Z 2024-10-16T12:00:12.148272Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Stopped watching for container logs. container_id=770635c191551373913981d9098f0c05eb8349ed2972e41406e7d3ff8eaa6861
2024-10-16T12:00:12.149066079Z 2024-10-16T12:00:12.148380Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Started watching for container logs. container_id=770635c191551373913981d9098f0c05eb8349ed2972e41406e7d3ff8eaa6861
2024-10-16T12:00:12.890198276Z 2024-10-16T12:00:12.890057Z ERROR source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Internal log [Received out of order log message.] has been rate limited 6 times.
2024-10-16T12:00:12.890384797Z 2024-10-16T12:00:12.890080Z ERROR source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Received out of order log message. error_type="condition_failed" stage="receiving" container_id="770635c191551373913981d9098f0c05eb8349ed2972e41406e7d3ff8eaa6861" timestamp="2024-10-16T12:00:10.269489804Z" internal_log_rate_limit=true
2024-10-16T12:00:12.890392557Z 2024-10-16T12:00:12.890112Z ERROR source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Internal log [Received out of order log message.] is being rate limited.
2024-10-16T12:00:12.890913040Z 2024-10-16T12:00:12.890729Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Stopped watching for container logs. container_id=770635c191551373913981d9098f0c05eb8349ed2972e41406e7d3ff8eaa6861
2024-10-16T12:00:12.925321103Z 2024-10-16T12:00:12.924823Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Started watching for container logs. container_id=770635c191551373913981d9098f0c05eb8349ed2972e41406e7d3ff8eaa6861
2024-10-16T12:00:37.854231740Z 2024-10-16T12:00:37.853923Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] has been rate limited 3 times.
2024-10-16T12:00:37.854263381Z 2024-10-16T12:00:37.853943Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"upcase\" at (475:515): expected string, got null" error_type="conversion_failed" stage="processing" internal_log_rate_limit=true
2024-10-16T12:00:37.854269101Z 2024-10-16T12:00:37.854068Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] is being rate limited.
```

**Comment by Geczy** [comment]
> none of that is relevant here, that all looks normal
> 
> can you run this in sql editor
> 
> select count(*) from pg_stat_activity;

84

**Comment by djsisson** [comment]
are all connections through 6543 or do you have any direct connections?

also can you run this

SELECT
  COUNT(*) as count,
  usename,
  application_name
FROM pg_stat_activity
WHERE application_name ILIKE '%Supavisor%'
GROUP BY
  usename,
  application_name
ORDER BY application_name DESC;

**Comment by djsisson** [comment]
in your other app add a connection timeout so the connections do not stay open, i think  the error is from the pooler being set to 20, but its hitting a connection limit and cant open anymore, presumable because of your other app, thats all i can think of

**Comment by djsisson** [comment]
or increase supabase max limit from 100

**Comment by Geczy** [comment]
can i add a connection timeout on the rest url? 

```http://supabase-kong-kk4wckkck0ogo0c8ookwsks0:8000```

**Comment by Geczy** [comment]
I meant to say I don't have any direct connections lol, I only use REST or 6543 Supavisor

**Comment by djsisson** [comment]
look through here,

SELECT 
    pid
    ,datname
    ,usename
    ,application_name
    ,client_hostname
    ,client_port
    ,backend_start
    ,query_start
    ,query
    ,state
FROM pg_stat_activity;

**Comment by djsisson** [comment]
nothing looks unusual, and you only had 84/100 total connection with 11 from pooler so why youre hitting connection limits i really dont know

**Comment by Geczy** [comment]
something's not right about this implementation, but i didn't have max connection issues with my old supavisor setup at https://github.com/coollabsio/coolify/pull/2712 and do with the new coolify template

this time it's 89/100 connections. why so many idle connections from supavisor_meta?

[supabase_default_Untitled query.csv](https://github.com/user-attachments/files/17461174/supabase_default_Untitled.query.csv)

**Pull request merged**
