### PR TITLE
Service/influxdb

### PR DESCRIPTION
**Pull request by mariusz-kraj**
## Changes
- New service template for InfluxDB

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
@mariusz-kraj  This is a service right so it is comparable to WordPress for example ofc for Database Management but it is not a Database like Redis or Postgres right?

**Comment by mariusz-kraj** [comment]
Hi, this is a database. Optimized for time-series data and used extensively in IoT projects where you need to store sensor data over time.

It's also great for energy-related projects because it's very easy to make calculate power/energy calculations.

**Comment by peaklabs-dev** [comment]
Thanks for the PR, this needs to be added to the codebase differently as a DB (I will leave this open for now).

**Comment by mariusz-kraj** [comment]
I'm happy to help. Is there any documentation on how to add a new database?

**Comment by peaklabs-dev** [comment]
No, there is no documentation, but you can check what files are needed by searching for an existing database such as `keydb`.

**Comment by peaklabs-dev** [comment]
Thanks for the PR. Databases should not be added as service templates, they need to be added differently to the codebase. You can search for `keydb` for example to see how other DBs have been added. Could you please update your PR with these changes? If you do not have time to do it this way, I will close the PR for now.

**Comment by mariusz-kraj** [comment]
I will have some time over the weekend. I'll do my best to update the PR

**Comment by peaklabs-dev** [comment]
Thank you for your contribution. Due to inactivity, we're closing this PR. If you'd like to revisit this change, feel free to reopen this PR or open a new pull request. I have also added a Discussion to track this https://github.com/coollabsio/coolify/discussions/4038

**Pull request closed without merging**
