### PR TITLE
Trigger.dev template fix to disable SSL mode for db and include port in db host url

### LINKED ISSUE #4213: [Bug]: Unable to deploy trigger.dev template because of SSL mode and wrong host
### Error Message and Logs

Hi, trying to deploy the latest `trigger.dev` template in v4.0.0-beta.364 gives two errors to `Electric` and `Trigger` containers;

`Electric` container gives this:
```
2024-11-09T10:01:30.220053317Z 10:01:30.219 [warning] Database connection in lock_connection mode failed: ssl not available
2024-11-09T10:01:30.220063645Z 
2024-11-09T10:01:30.220066546Z 10:01:30.219 [warning] Reconnecting in 2000ms
2024-11-09T10:01:32.222592759Z 
2024-11-09T10:01:32.222618467Z 10:01:32.222 [warning] Database connection in lock_connection mode failed: ssl not available
2024-11-09T10:01:32.222622165Z 
2024-11-09T10:01:32.222633540Z 10:01:32.222 [warning] Reconnecting in 4000ms
2024-11-09T10:01:36.224926071Z 
2024-11-09T10:01:36.224951288Z 10:01:36.224 [warning] Database connection in lock_connection mode failed: ssl not available
2024-11-09T10:01:36.224954887Z 
2024-11-09T10:01:36.224957387Z 10:01:36.224 [warning] Reconnecting in 8000ms
```

`Trigger` container gives this:
```
2024-11-09T10:02:53.219278610Z + [ -n postgresql ]
2024-11-09T10:02:53.219297348Z + scripts/wait-for-it.sh postgresql -- echo database is up
2024-11-09T10:02:53.220560527Z Unknown argument: postgresql
2024-11-09T10:02:53.220642907Z Usage:
2024-11-09T10:02:53.220647605Z   scripts/wait-for-it.sh host:port|url [-t timeout] [-- command args]
2024-11-09T10:02:53.220650144Z   -q | --quiet                        Do not output any status messages
2024-11-09T10:02:53.220652563Z   -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
2024-11-09T10:02:53.220655163Z   -- COMMAND ARGS                     Execute command with args after the test finishes
```

The SSL issue seems to be because Electric enables SSL mode as default according to here https://electric-sql.com/blog/2024/01/24/electricsql-v0.9-released#ssl-encrypted-database-connections-by-default

I tried setting ENV `DATABASE_REQUIRE_SSL: false` but wasnt able to get it to work. It did work when I updated the database url to include `?sslmode=disable` though (alternative solution here https://legacy.electric-sql.com/docs/api/service#database_require_ssl

I think the best option would be to enable SSL mode for postgres but it seems to involve more steps to be able to enable it, if you know any easy way to include it in the template, it would be better.

The second error in Trigger container seems to come from database host missing the port here https://github.com/coollabsio/coolify/blob/main/templates/compose/trigger.yaml#L23 when I changed it to `postgresql:5432` the service was able to start.

I created a PR for it.

### Steps to Reproduce

1. Search for trigger.dev template in Coolify v4.0.0-beta.364
2. Deploy
3. Wait for services to try being healthy
4. Check `Electric` and `Trigger` container logs after 30 seconds.

### Example Repository URL

_No response_

### Coolify Version

v4.0.0-beta.364

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.5 LTS

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by beejaz**
## Changes
- Disable SSL for postgres database connection
- Change database host to include port

## Issues
- fix #4213

### CODE REVIEW

**Review by Yoda-Soda — APPROVED** [review]
Works well thank you for the fix.

**Comment by Yoda-Soda** [comment]
I did run into some issues creating a Personal Access Tokens via the cli or manually, dunno if it's me a issue or a trigger issue or an issue related to the docker compose config. Worth confirming before mering.

**Comment by beejaz** [comment]
> I did run into some issues creating a Personal Access Tokens via the cli or manually, dunno if it's me a issue or a trigger issue or an issue related to the docker compose config. Worth confirming before mering.

Yes, Im stuck at that issue also. I dont think it is related to this PR but im still trying to find the reason it gives:
```
Authentication failed
Invalid key length

There was a problem authenticating you, please try logging in with your CLI again.
```

After opening URL from CLI `<domain>/account/authorization-code/2U2Nnj33rq1t0A51jnXodbVdNvkzc8DwwfhJ1UxMltOISYH39QxuFGNKmMN2J_ur`

CLI command:
`bunx trigger.dev@latest init -p proj_ymhcwzuyrpbosgykwagl -a https://<domain> -l debug`

**Comment by Yoda-Soda** [comment]
yeah that's exactly the same issue I have. I've created a bug report on trigger to see I can get more info.

**Comment by matt-aitken** [comment]
Hey, I'm one of the cofounders of Trigger.dev.

Those errors are invalid key lengths are because your not generating the correct length encryption keys. From our self-hosted docs:

```
echo MAGIC_LINK_SECRET=$(openssl rand -hex 16)
echo SESSION_SECRET=$(openssl rand -hex 16)
echo ENCRYPTION_KEY=$(openssl rand -hex 16)
echo PROVIDER_SECRET=$(openssl rand -hex 32)
echo COORDINATOR_SECRET=$(openssl rand -hex 32)
```

I don't use Coolify but my guess is that you need to use `BASE64` instead of `PASSWORD` for the first 3, and `BASE64_64` for the last two. I know for sure that the `ENCRYPTION_KEY` must be the correct length and that's why you're seeing that error when using the CLI.

**Comment by peaklabs-dev** [comment]
@matt-aitken Nice to see you here on the Coolify repo.

I am a core developer of Coolify and I am currently refactoring our magic env variabels. The new magic will be able to generate hexadecimal secrets of any length you want. And from your message and the `openssl` commands I see that Trigger needs random hexadecimal secrets all in lowercase is that correct? or is it also possible to use no hexadecimal characters?

**Pull request merged**
