### PR TITLE
enhance: Formbricks template add required CRON_SECRET

### PR DESCRIPTION
**Pull request by LaurenceJJones**
https://github.com/formbricks/formbricks/issues/2874

A new required env var has been added, using special magic to generate a random password as the value to abstract away from user.

> Always use `next` branch as destination branch for PRs, not `main`

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Changing the destination to `next` branch added a bunch of files 😕 let me know if I messed up :D

**Comment by Shubhamzingare** [comment]
image
this issue is still there

**Comment by LaurenceJJones** [comment]
> image this issue is still there

Yes because the PR is not merged, the self rectify add a environment variable to the compose manually.

**Comment by LaurenceJJones** [comment]
Closing PR to attempt to fix the extra files

**Comment by LaurenceJJones** [comment]
Superseded by #2954

**Pull request closed without merging**
