### PR TITLE
feat: add Mixpost template

### PR DESCRIPTION
**Pull request by AlejandroAkbal**
This PR adds a Mixpost template

https://mixpost.app/
https://docs.mixpost.app/

Default User Credentials:
Email:    admin@example.com
Password: changeme

### CODE REVIEW

**Comment by DeVoresyah** [comment]
hi @andrasbacsai , can you take a look on this?

**Comment by DeVoresyah** [comment]
hi @andrasbacsai , can this one merged in the next release?

**Comment by Gruce** [comment]
+1

**Comment by andrasbacsai** [comment]
Thank you for the PR!

**Pull request merged**
