### PR TITLE
feat: Add Pterodactyl

### PR DESCRIPTION
**Pull request by Telokis**
This PR adds support for [Pterodactyl](https://pterodactyl.io/), the game server manager.

I have properly tested it and it works fine but it needs some manual intervention to be perfect.

@andrasbacsai  We'll need to decide how to communicate the following additional steps required once the services are deployed:

```md
## Instructions:
- Run `chown -R nginx: /app/storage/logs/` in the pterodactyl container to ensure you get proper error logs in the future
- Wait for the Pterodactyl service to be healthy (can take a few minutes)
- Use the command `php artisan p:user:make --no-interaction --admin=1 --email=<email> --username=<username> --name-first=<firstname> --name-last=<lastname> --password=<password>` in the Pterodactyl container to create an admin user.
- Login to the panel using the created user
- Go to the Admin panel (Cog icon at the top)
- Go to "Locations" on the left
- Create a new location
- Go to "Nodes" on the left
- Create a new node
  - The FQDN and HTTPS depend on the settings you've set in Coolify but omit the protocol (`example.com` instead of `https://example.com`)
  - Check "Behind Proxy"
  - For the Daemon port, specify 80 if you use HTTP. Specify 443 is you use HTTPS
- Go to the "Configuration" tab of your newly created node
- Copy the configuration file
- In Coolify go to the "Storage" menu for your resource.
- Find the big text area associated with `config.yml` for Wings
- Paste the configuration at the top of this file, above `docker:`
- Change the `api.port` field to use the port `8080`
- Save the file
- Go to the "About" tab and confirm that the "Information" section shows the "Daemon Version" properly.
```

<details>

<summary>Expected output of user creation</summary>

If your command to create the user was properly done, you should see an output similar to the one below:

```
+----------+--------------------------------------+
| Field    | Value                                |
+----------+--------------------------------------+
| UUID     | 6b3083ca-274b-4a77-a88f-6fbf5e4f286f |
| Email    | admin@example.com                    |
| Username | admin                                |
| Name     | Super Admin                          |
| Admin    | Yes                                  |
+----------+--------------------------------------+
```

</details

Those steps are required to have things working as expected.

### CODE REVIEW

**Comment by Telokis** [comment]
The two comments I've left point to the following message from the Pterodactyl Discord.

Screenshot_1

**Comment by xXKynarethXx** [comment]
Nice, really looking forward, thanks for your work! 🔥

**Comment by DutaKey** [comment]
@Telokis Hi bro, can I have your contact information, I'd like to ask you a few questions about this.

**Comment by BossDarkReaper** [comment]
Would be great if we could deploy the panel and nodes separately

**Comment by Telokis** [comment]
> Would be great if we could deploy the panel and nodes separately

@BossDarkReaper Yes. For your own needs, you can take only a part of the `docker-compose.yml` and adjust it accordingly. It should work.

**Comment by maximocitba** [comment]
Can't wait for this merge

**Comment by peaklabs-dev** [comment]
@Telokis I think you could remove the first 3 steps and create a command in the compose file that does them automatically to make this easier/ set password and so on in the compose (the rest still needs to be done manually). I will add the rest of the steps to the docs, I think the first 3 steps should be made into something like this - you could also use envs in the command to make it even better:
```yaml
 command: >
      sh -c "
        chown -R nginx: /app/storage/logs/ &&
        php artisan p:user:make --no-interaction --admin=1 
        --email=admin@example.com 
        --username=admin 
        --name-first=Admin 
        --name-last=User 
        --password=yourpassword
      "

```

What do you think? If it is possible, please make this change as it will make the installation much easier.

**Comment by louanfontenele** [comment]
Any chance we can have ptero on coolify?

**Comment by peaklabs-dev** [comment]
@Telokis Not sure if you are still working on this but if you have time can you take a look at the change idea I proposed.

**Comment by peaklabs-dev** [comment]
Thank you for your contribution. Due to inactivity, we're closing this PR. If you'd like to revisit this change, feel free to reopen this PR or open a new pull request.

**Comment by Telokis** [comment]
Hello!

Sorry, I've indeed moved on since making this PR.  
I've been using the setup described in this PR since then and it's been working perfectly.  

As I've moved on to other things I don't really have the motivation to perform any changes here for now, I'm sorry.  
Feel free to use my contribution however you or anyone wishes, no problem.

**Comment by xXKynarethXx** [comment]
@Telokis thanks for your work so far ❤️
I only want it to be reopen so @andrasbacsai can merge it if he has time for it, as its already ready

thanks again and have a nice day!

**Comment by peaklabs-dev** [comment]
All right, I understand, I cannot guarantee I will get it to work, but I will give it a fair shot.

**Comment by peaklabs-dev** [comment]
Good news, I got a semi-automated install working, but it is not fully working yet, so I leave it disabled for now. Of course if someone wants to pick it up, just open a PR. Sorry for closing it first, merging makes more sense, especially since it almost works.

**Pull request merged**
