### PR TITLE
Feat: Add Webhook/ External notification provider

### PR DESCRIPTION
**Pull request by nullishamy**
Should allow the bottom entry of https://github.com/coollabsio/coolify/issues/2526#issuecomment-2178828539 to be closed off. 

This adds the ability to use an external webhook for notifications.

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
@nullishamy Sorry for the late review. I have completed the refactored notifications for the next release and if you still have time and are able to work on this PR, it would be necessary to adjust your PR according to the new notification handling. You can check my PR to see the migrations and models added: https://github.com/coollabsio/coolify/pull/4525 and you can check out the `next` branch for now to see the new way of implementing notifications. 

It would be great if you could adjust your PR accordingly. If you are unable to do so, please let me know so I can close this PR.

**Comment by nullishamy** [comment]
So what actually changed, notification settings? Should I expect more changes to come wrt notifications before I start work on this again?

**Comment by peaklabs-dev** [comment]
@nullishamy It is completed so everything should be final (only bugs if any). 

Changed: New database structure + models, more/new Notifications and new settings views with more granular control (take a look at the PR to get a better understanding at the new migrations table setup, model and view strucuture).

I would suggest closing this PR and opening a new PR a lot of changes you made can be taken from this one but a lot of things are new.

Also I think Webhook notifications would probably be a more suiteable name then external notifications or what do you think?

**Comment by nullishamy** [comment]
Right. We can debate names separately. I was already planning on redoing it because of the merge conflicts.

**Comment by nullishamy** [comment]
Closing as the usecase that was going to be supported by this for our deployment (better Discord notifications) has been addressed on its own in the 6 months between this PR being open and now. Additionally lack of motivation to rewrite the whole PR.

**Pull request closed without merging**
