### PR TITLE
add pterodactyl panel service

### PR DESCRIPTION
**Pull request by davidollmann**
Service for the game server panel [pterodactyl](https://github.com/pterodactyl/panel)

You can find more information on this service on their website [pterodactyl.io](https://pterodactyl.io/)
They also support third party add-ons called eggs. A list of them is here [github.com/parkervcp/eggs](https://github.com/parkervcp/eggs)

I tested it with a private gitpod environment (using exposed port) and with a fresh linux vm (using traefik). Seems to work smoothly.

Sidenote: I am not affiliated to the pterodactyl project.

### CODE REVIEW

**Comment by andrasbacsai** [comment]
Sorry, I have to close this PR without merging. The services changed since then. Now, there are [template-based](https://github.com/coollabsio/coolify-community-templates) services. I will add pterodactyl to the list!

**Comment by itorz7** [comment]
Is there now?

**Comment by davidollmann** [comment]
> Is there now?

I just added a pr on the new template repository [#20](https://github.com/coollabsio/coolify-community-templates/pull/20)

**Comment by Telokis** [comment]
Working on it at https://github.com/coollabsio/coolify/pull/3052.  
Still a few caveats to fix.

**Pull request closed without merging**
