### PR TITLE
feat: Add Supertokens template

### PR DESCRIPTION
**Pull request by marcomaiermm**
This PR adds [Supertokens](https://supertokens.com/) as a service to coolify using a slightly modified version of their provided docker-compose.

Official docs: [https://supertokens.com/docs/guides](https://supertokens.com/docs/guides)

Official docs running with docker: [https://supertokens.com/docs/community/supertokens-core/self-hosted/with-docker](https://supertokens.com/docs/community/supertokens-core/self-hosted/with-docker)

### CODE REVIEW

**Comment by RivierGrullon** [comment]
any change of getting this template? 👀

**Comment by Netflixyapp** [comment]
Is this PR missing something? Can this template be included in the next release? Thanks

**Comment by marcomaiermm** [comment]
> Is this PR missing something? Can this template be included in the next release? Thanks

I think it should be ready :)
Can you have a look on this @andrasbacsai ? Any thoughts?

**Comment by peaklabs-dev** [comment]
I have tested this service and it seems to work properly. Thanks for your PR 💜.

**Comment by peaklabs-dev** [comment]
I will also add the mysql version as this PR was only for Postgresql

**Pull request merged**
