### PR TITLE
Feat: getoutline service

### PR DESCRIPTION
**Pull request by peaklabs-dev**
https://github.com/coollabsio/coolify/discussions/3179

### CODE REVIEW

**Comment by somteacodes** [comment]
I tested this PR with the latest version of Outline (0.79.0) and found a couple of issues:

Fix: Added `PGSSLMODE=${PGSSLMODE:-disable}` to the outline service environment variables. This resolves the error: "The database does not support SSL connections."

Additionally, the latest version of Outline fails to start due to the health check. 
Disabling the health check for the outline service is a workaround as described in [this issue](https://github.com/outline/outline/issues/7547):
```
healthcheck:
  disable: true
```
  
(Optional) adding `SERVICE_FQDN_OUTLINE_3000` to the outline service environment.

**Comment by Sulcalibur** [comment]
Is Outline available in the Resources now? I updated Coolify to v4.0.0.beta341 but still can't see it there?

**Comment by somteacodes** [comment]
> Is Outline available in the Resources now? I updated Coolify to v4.0.0.beta341 but still can't see it there?

No, it's not available yet as of v4.0.0.beta341, but it will be once this PR is merged.

I use Outline with Docker Compose on coolify and was planning to create a template myself. However, I noticed this PR and decided to test it. During my testing, I identified a few issues that I wanted to point out.

**Comment by peaklabs-dev** [comment]
@somteacodes Thanks for the feedback. At the moment we are focused on bugfixes and introducing the last features for v4 stabel so currently new templates are not getting merged.

**Comment by Sulcalibur** [comment]
> > Is Outline available in the Resources now? I updated Coolify to v4.0.0.beta341 but still can't see it there?
> 
> No, it's not available yet as of v4.0.0.beta341, but it will be once this PR is merged.
> 
> I use Outline with Docker Compose on coolify and was planning to create a template myself. However, I noticed this PR and decided to test it. During my testing, I identified a few issues that I wanted to point out.

Superstar! Thank you and all others involved

**Comment by peaklabs-dev** [comment]
@Sulcalibur I have not really been able to test Outline, it would help if you could test it now that it is out and report any issues you find. Thanks in advance.

**Pull request merged**
