### PR TITLE
Fix caddy quic udp port

### PR DESCRIPTION
**Pull request by lynt-smitka**
## Changes
- Expose port 443/udp for Caddy proxy (to enable QUIC/HTTP3)

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
Thank you for your contribution. This was added via this PR: https://github.com/coollabsio/coolify/pull/3853 so this PR is no longer needed.

**Comment by andrasbacsai** [comment]
#3853 was for Traefik, so I think this one is still needed.

**Comment by peaklabs-dev** [comment]
Ups, sorry about that.

**Comment by peaklabs-dev** [comment]
Thanks for the PR no I am merging it:)

**Pull request merged**
