### PR TITLE
[WIP]: Improve logs

### PR DESCRIPTION
**Pull request by yohannlog**
[ UPDATED 24/06/2024 ]

I've decided to completely overhaul the way logs are managed. The current system doesn't save logs, and this is a major problem. What's more, adding a backup system on top of the old one is quite restrictive. That's why I decided to implement several things:

Major change:
- [ ] Create a service dedicated to logging. (https://github.com/yohannlog/coolify-logs)
- [ ] Add API support
- [ ] Send logs to this service

Features:
- [ ] Save logs in files ( {container_id}/{dd_mm_yy.csv} ) with rotation and file size limits
- [ ] Save logs in database
- [ ] Send logs to custom service ?
- [ ] Add a page dedicated to logs with history (New button to left menu)
- [ ] Add "Show more" buttons on large logs
- [ ] Supports ANSI color format
- [ ] Add tabs when multiple servers in one page
- [x] Add a "Download button"
- [ ] Add a checkbox to download using max lines
- [ ] Add type="number" to max lines input
- [ ] Add search filter
- [ ] Add option to download logs on only filtered logs
- [ ] Add styles to logs ?
- [x]  Add a wrap lines checkbox so that log lines are automatically wrapped (to viewport size).
- [ ] Save wrap lines option
- [ ] Add style for + and - button (For wrapping lines)
- [ ] Make time clickable to filter logs
- [ ] Review the code in GetLogs.php to simplify it (duplicate code, etc.).

This PR or later
- [ ] Manage json logs format

If I need to, I'll make a design modification to keep it readable and understandable.

### CODE REVIEW

**Comment by ayntk-ai** [comment]
No idea if this can work but for logs that are very long a wrap lines feature would be handy:

- [ ] Add a wrap lines checkbox so that log lines are automatically wrapped (to viewport size).

**Comment by yohannlog** [comment]
For the moment, I did that:
image

**Comment by ayntk-ai** [comment]
@yohannlog Looks amazing. Thank you so much.

**Comment by ayntk-ai** [comment]
>  Add styles to logs ?
@yohannlog  I think this would be possible, for example, errors could be highlighted in red, success in green, warning in orange/yellow and the rest in white.

**Comment by yohannlog** [comment]
> >  Add styles to logs ?
> 
> @yohannlog  I think this would be possible, for example, errors could be highlighted in red, success in green, warning in orange/yellow and the rest in white.

The only thing I can test is show colors from logs generated by an application. It is complicated to determine what log type it is.

**Comment by iamEvanYT** [comment]
> The only thing I can test is show colors from logs generated by an application. It is complicated to determine what log type it is.

Showing colors generated by an application sounds cool.

**Comment by yohannlog** [comment]
I've added a discussion about this PR: #2618

**Comment by yohannlog** [comment]
[ PR TEXT UPDATED ]

**Comment by ayntk-ai** [comment]
@yohannlog I am not sure if the maintainer is interested in starting an additional container, at least I would want to run as few containers for such things as possible, just for logs, is this really needed? Maybe there is a way to do this without needing another container?

**Comment by peaklabs-dev** [comment]
This pull request is currently in draft status. We would like to merge the currently available changes, please take the PR out of draft status. If no action is taken, this PR will be closed for inactivity.

**Comment by peaklabs-dev** [comment]
If you decide to work on this again, feel free to open a new PR that is also up to date with the latest available version.

**Pull request closed without merging**
