### PR TITLE
Upgrade Appwrite service template to 1.5

### PR DESCRIPTION
**Pull request by estubmo**
### Service Changes
- Removed `appwrite-influxdb` and related env vars
- Removed `appwrite-telegraf` and related env vars
- Replaced `appwrite-usage` with `appwrite-worker-usage` and `appwrite-worker-usage-dump`
- Replaced `appwrite-schedule` with `appwrite-scheduler-functions` and `appwrite-scheduler-messages`
- Enabled `appwrite-assistant`
- Updated Redis and MariaDB versions
- Added additional env vars to `appwrite-worker-messaging`

### Added new env vars:
- _APP_MAINTENANCE_DELAY
- _APP_CONSOLE_HOSTNAMES

Would like feedback on whether this should be the default: `_APP_CONSOLE_HOSTNAMES=localhost,appwrite.io,*.appwrite.io`

### CODE REVIEW

**Comment by compgeniuses** [comment]
thank you for the update,

However i am curious in regards to this..
Would like feedback on whether this should be the default: _APP_CONSOLE_HOSTNAMES=localhost,appwrite.io,*.appwrite.io

**Comment by estubmo** [comment]
> However i am curious in regards to this..
> Would like feedback on whether this should be the default: _APP_CONSOLE_HOSTNAMES=localhost,appwrite.io,*.appwrite.io

I suppose this is something the user should get prompted to define himself, depending on the FQDN

**Comment by andrasbacsai** [comment]
I cannot find `_APP_CONSOLE_HOSTNAMES` in their [docs](https://appwrite.io/docs/advanced/self-hosting/environment-variables#general). Where did you get it from?

**Comment by MHEien** [comment]
@andrasbacsai ``Add `_APP_CONSOLE_HOSTNAMES` env var to allow more hostnames to the console project by @stnguyen90 in https://github.com/appwrite/appwrite/pull/7377``
[https://github.com/appwrite/appwrite/blob/f7e6d516efe3afbf6ee2343fd99a9d5692379076/CHANGES.md?plain=1#L131](https://github.com/appwrite/appwrite/blob/f7e6d516efe3afbf6ee2343fd99a9d5692379076/CHANGES.md?plain=1#L131)

**Comment by estubmo** [comment]
All default env vars can be found here: https://github.com/appwrite/appwrite/blob/f7e6d516efe3afbf6ee2343fd99a9d5692379076/.env

**Comment by estubmo** [comment]
Sorry, it happened unintentionally when I was syncing my fork.

**Comment by lucasdidur** [comment]
When this will come out?

**Comment by estubmo** [comment]
I guess whenever @andrasbacsai feels like reviewing and merging it.

**Comment by lucasdidur** [comment]
@andrasbacsai can you give some attention here, this update adds great things on AppWrite

**Comment by estubmo** [comment]
> @andrasbacsai can you give some attention here, this update adds great things on AppWrite

In the meantime, what you can do, is to create an existing Appwrite service and copy paste the contents of https://github.com/coollabsio/coolify/blob/4d8553f95996411142efa6d554df0614c2c9032f/templates/compose/appwrite.yaml into the textarea for Edit Compose File on Coolify.

Remember to add new env variables as well.

**Comment by lucasdidur** [comment]
@estubmo There is 2 `version: '3'` lines in this file

**Pull request merged**
