### PR TITLE
Add comet, self hosted stremio addon template.

### PR DESCRIPTION
**Pull request by yokowasis**
## Changes
-  Add comet, self hosted stremio addon template.

### CODE REVIEW

**Comment by yokowasis** [comment]
- INDEXER_MANAGER_INDEXERS must be set as literal.
- INDEXER_MANAGER_API_KEY can be retrieved from the jackett fqdn domain. as of right now, the api can't be set from environment. CMIIW.

**Comment by peaklabs-dev** [comment]
> INDEXER_MANAGER_API_KEY can be retrieved from the jackett fqdn domain. as of right now, the api can't be set from environment. CMIIW.

What do you mean by this? does it need the fqdn instead of the URL or what key does it need from the logs?

**Comment by yokowasis** [comment]
to get the INDEXER_MANAGER_API_KEY environment value, you need to open web
interface of jackett.

1. deploy the docker compose.
2. open the jacket web interface
3. copy the api key
4. paste it on coolify
5. restart / redeploy the service.

**Comment by andrasbacsai** [comment]
Hey @yokowasis, I appreciate your efforts, but I'll have to decline this PR. 

They're currently too small or new for us to effectively maintain on our side. 

We're always on the lookout for promising services, so feel free to keep us updated as they develop further.

**Pull request closed without merging**
