### PR TITLE
Service: osticket

### PR DESCRIPTION
**Pull request by kanhaic**
## Changes
- Added Service osticket

## Issues
- fix #3850

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
Is it normal that it shows this page? How can I login (never used this service before)?
image

**Comment by kanhaic** [comment]
This is a successful install. you can login with {{url}}/scp with the username and password that you set.

**Comment by peaklabs-dev** [comment]
Thank you for the PR 💜. I will test it and fix it if necessary.

**Comment by kanhaic** [comment]
👍🏼

**Comment by peaklabs-dev** [comment]
I fixed it, now you can access Osticket directly from the domain:
image

**Comment by kanhaic** [comment]
Where can I see your changes?

**Comment by peaklabs-dev** [comment]
You can check out this commit: https://github.com/coollabsio/coolify/pull/3838/commits/77600e9f461f4f27457c1fa78c6fecde3f38c09a

**Pull request merged**
