### PR TITLE
add endpoints for filtering applications by domain and managing conta…

### PR DESCRIPTION
**Pull request by samirimtiaz1996**
…iner labels

- Add /api/v1/domains?uuid={application_uuid} endpoint (GET) to filter applications by domains for a given project UUID
- Add /api/v1/domains endpoint (PUT) to update domains and regenerate container labels
- Add /api/v1/domains endpoint (DELETE) to delete domains and regenerate container labels

> Always use `next` branch as destination branch for PRs, not `main`

### CODE REVIEW

**Comment by samirimtiaz1996** [comment]
add endpoints for filtering applications by domain, update and delete domains for specific application uuid with updating container labels. If you see any changes you'd like to make, please let me know.

**Comment by samirimtiaz1996** [comment]
add endpoints for filtering applications by domain, update and delete domains for specific application uuid with updating container labels. If you see any changes you'd like to make, please let me know.

**Comment by samirimtiaz1996** [comment]
add endpoints for filtering applications by domain, update and delete domains for specific application uuid with updating container labels. If you see any changes you'd like to make, please let me know.

**Comment by andrasbacsai** [comment]
Very nice! Thank you very much!

**Comment by ZatiqDev** [comment]
🚫 The functionality to add the /api/v1/domains endpoint (PUT) for updating domains and regenerating container labels hasn’t been merged into the master branch yet.
In app/Http/Controllers/Api/Applications.php file, from line 68 to 78 has been commented out which can perform the mentioned functionality.
Could you please provide some context on why the functionality is commented out and approximately when it will be added into the master branch?

**Comment by samirimtiaz1996** [comment]
🚫 The functionality to add the /api/v1/domains endpoint (PUT) for updating domains and regenerating container labels hasn’t been merged into the master branch yet.
In app/Http/Controllers/Api/Applications.php file, from line 68 to 78 has been commented out which can perform the mentioned functionality.
Could you please provide some context on why the functionality is commented out and approximately when it will be added into the master branch?

**Pull request merged**
