### PR TITLE
feat: add Plane as a template

### PR DESCRIPTION
**Pull request by SaadBazaz**
/claim #2354

### CODE REVIEW

**Comment by SaadBazaz** [comment]
Needs testing

**Comment by andrasbacsai** [comment]
Thank you for the PR!

It looks good, but I would like to ask for some modifications.

1. As I see you defined a shared configuration called `x-app-env` but you never reused it, so please remove it.
2. If a service in the stack does not requires all the env variables, do not define them (like for  `plane-minio`, it only needs 2 - see [here](https://github.com/makeplane/plane/blob/preview/docker-compose.yml#L124))
3. Please use Coolify's autogenerator magic (read more [here](https://coolify.io/docs/knowledge-base/add-a-service)) to generate passwords, usernames, fqdns (`like WEB_URL`), etc, especially in database passwords and secrets.

**Comment by DeVoresyah** [comment]
hi @SaadBazaz can you take a look on the feedback?

**Comment by SaadBazaz** [comment]
Thank you @andrasbacsai for such a descriptive feedback. Love your work. 

@DeVoresyah Sure I'll check it out.

**Comment by cr4zyiw4n** [comment]
hi,
this lines are broken:
    - 'REDIS_URL=${REDIS_URL:-redis://${REDIS_HOST}:6379/}'
    - 'DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PGHOST}/${PGDATABASE}}'
if i remove them i get:
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/takeoff": stat ./bin/takeoff: no such file or directory: unknown

**Comment by DeVoresyah** [comment]
any updates on this @SaadBazaz ?

**Comment by andrasbacsai** [comment]
Closing this because there was not response.

**Pull request closed without merging**
