### PR TITLE
JupyterLab Notebook with C++ (xeus-cling) and Javascript (Deno) Kernel

### PR DESCRIPTION
**Pull request by yokowasis**
## Changes
- Add Jupyterlab template
- Ubuntu as image

### CODE REVIEW

**Comment by peaklabs-dev** [comment]
I do not know enough about `jupyterlab`, what do you think about this template https://github.com/coollabsio/coolify/blob/services/templates/compose/jupyter-notebook.yaml that was added recently?

**Comment by yokowasis** [comment]
That one can only run python code.

This one can run python, c++, and Javascript.

Also you can install additional package using environment variable.

**Comment by yokowasis** [comment]
I personally use this image to teach my students c++, jupyter is great for
experiment and teaching, which is why it's loved by the academic and
researcher.

**Comment by andrasbacsai** [comment]
Hey @yokowasis,

Unfortunately, we won't add this service to the official list, as it involves installing third-party components into a simple Docker image.

We will soon define the exact criteria for what can be added to the service list.

If you use the Docker Compose buildpack and copy-paste this compose file, it will still work as is.

Sorry about that. I am closing this PR.

**Pull request closed without merging**
