### PR TITLE
fix: Fix Huly template

### PR DESCRIPTION
**Pull request by Telokis**
This PR finalizes the [Huly](https://huly.io/) template to make it work properly:

- Add a logo (Not required but always nice)
- Remove `ignore: true` because the template works fine
- Add auto-generated [USER](https://coolify.io/docs/knowledge-base/add-a-service#username) and [PASSWORD](https://coolify.io/docs/knowledge-base/add-a-service#password) to `minio`
- Fix all links from service to service because most of them must be public-facing links
- Use `latest` images by default

Non-blocking caveats (cc @andrasbacsai):
- During my testing, I noticed that `SERVICE_URL_HULYCOLLABORATOR` and `SERVICE_URL_HULYTRANSACTOR` were not auto-set in the `Environment variables` tab and I had to manually define them. I don't know if it's a bug or a behavior I haven't properly understood.
- For websockets, I had to do `COLLABORATOR_URL=wss://$SERVICE_URL_HULYCOLLABORATOR` which explicitely uses `wss` (secure websockets) that only work in `https`. Do you think it would be relevant to create some kind of `SERVICE_FQWS_*` that automatically chooses between `ws` and `wss` like `SERVICE_FQDN_*` does?
- The line `FRONT_URL=${HULY_FRONT_PUBLIC_FQDN:-$SERVICE_FQDN_HULYFRONT}` is directly related to https://github.com/coollabsio/coolify/issues/3048 that I created after encountering the problem.

/claim #2543

### CODE REVIEW

**Comment by action-simon** [comment]
Hello, I tried to run the file, and I noticed that some secrets are there twice, is this wanted behavior?

image
image

Also I noticed, when I try to create a workspace it get's stuck at 30% any ideas?

**Comment by Telokis** [comment]
> Hello, I tried to run the file, and I noticed that some secrets are there twice, is this wanted behavior?
> 
> Also I noticed, when I try to create a workspace it get's stuck at 30% any ideas?

@action-simon Hey! The doubled variables is a weird behavior from Coolify, nothing I can do myself but I might have misunderstood something related to magic SERVICE variables.  

Regarding the 30% bug, see [my response](https://discord.com/channels/459365938081431553/1277216005160173620/1277216355669508166) on Discord.

**Comment by WEBzaytsev** [comment]
> > Hello, I tried to run the file, and I noticed that some secrets are there twice, is this wanted behavior?
> > Also I noticed, when I try to create a workspace it get's stuck at 30% any ideas?
> 
> @action-simon Hey! The doubled variables is a weird behavior from Coolify, nothing I can do myself but I might have misunderstood something related to magic SERVICE variables.
> 
> Regarding the 30% bug, see [my response](https://discord.com/channels/459365938081431553/1277216005160173620/1277216355669508166) on Discord.

Hello! It was not possible to access your answer in discord, can you write here how to fix it?

**Comment by florinmtsc** [comment]
Hi, thanks for taking the time to create this. I managed to have it working but only until creating the workspace.

I get this error unfortunately: `{"account":"test@example.com"},"severity":"ERROR"},"timestamp":"2024-09-11T16:06:17.727Z"}
2024-09-11T16:06:24.737455229Z {"account":"test@example.com","level":"info","message":"account created","timestamp":"2024-09-11T16:06:24.737Z"}
2024-09-11T16:06:40.121932158Z {"email":"test@example.com","level":"info","message":"Creating workspace","timestamp":"2024-09-11T16:06:40.121Z","workspaceName":"example"}
2024-09-11T16:06:40.144617539Z {"email":"test@example.com","level":"info","message":"Creating user side done","timestamp":"2024-09-11T16:06:40.144Z","workspaceName":"example"}
2024-09-11T16:08:28.138891729Z {"err":{"message":"Not enough or too many segments","stack":"Error: Not enough or too many segments\n    at vse.decode (/usr/src/app/bundle.js:228:155957)\n    at decodeToken (/usr/src/app/bundle.js:228:158638)\n    at decodeToken (/usr/src/app/bundle.js:303:195931)\n    at selectWorkspace (/usr/src/app/bundle.js:303:196157)\n    at /usr/src/app/bundle.js:303:224703\n    at /usr/src/app/bundle.js:340:36007\n    at t.with (/usr/src/app/bundle.js:7:3547)\n    at /usr/src/app/bundle.js:340:35979\n    at i (/usr/src/app/bundle.js:315:277842)\n    at /usr/src/app/bundle.js:340:28321"},"level":"error","message":"error","status":{"code":"platform:status:InternalServerError","params":{},"severity":"ERROR"},"timestamp":"2024-09-11T16:08:28.138Z"}
2024-09-11T16:08:37.505270715Z {"email":"test@example.com","level":"info","message":"login success","timestamp":"2024-09-11T16:08:37.504Z"}`


does this happen to you? I didn't find any information on huly issues or nowhere else. I setup like you above.

**Comment by florinmtsc** [comment]
Also there may be a need for traefik labels to be added because there are 4 public urls and I used to get CORS error. (e..g front example.com and account on account.example.com results in CORS). The solution is to use prefix and add traefik labels to redirect to the right service (e.g. example.com -> front, example.com/account -> account, etc)

**Comment by Telokis** [comment]
I will close this PR because the setup doesn't seem to work anymore and I have no idea why.

**Pull request closed without merging**
