### PR TITLE
Generate labels by proxy type

### PR DESCRIPTION
**Pull request by lorenzomigliorero**
fix: https://github.com/coollabsio/coolify/issues/2801

When I started playing with Coolify, I found it confusing that the docker-compose always contains Caddy and Traefik labels.
Also, this solution will be more scalable once more proxies are supported. The drawback is the deployable docker-compose needs to be manually re-generated when the server proxy changes.

### CODE REVIEW

**Comment by andrasbacsai** [comment]
I have mixed feelings about this. Why do you think it is not scalable?

**Comment by lorenzomigliorero** [comment]
Hi @andrasbacsai! First of all, great job! Yes, you can have any number of labels, but most of them won't be active since only 1 proxy can be selected at a time. So, the more proxies we support, the messier the container will be. Scoring the labels to the proxy means there won't be a similar issue. But I agree, it only improves the compose readability; it'll work in both cases. It's up to you! I thought it'd be a nice addition, the first evening I played with Coolify it took me 3 hours to figure out why caddy labels weren't working.

**Comment by andrasbacsai** [comment]
Sounds good. I think if it were a setting, that would be good.

For beginners, Coolify will generate both labels, because they just don't care or have no idea how they work.

For advanced users, they can turn on this setting, so they only get the proxy-specific labels.

What do you think?

**Comment by lorenzomigliorero** [comment]
It makes sense, yeah. Even if I don't see beginners switching proxies too often, the default compose will be a ready-to-go solution for everyone. I'll take a look at this [PR](https://github.com/coollabsio/coolify/pull/2863) to see how a new flag can be added. Just a question: is there a linter to set up on the project? I guess the editor config is the source of truth, but maybe you've some suggestions? I'm using VS Code.

**Comment by andrasbacsai** [comment]
I can add the flag easily in a few minutes. Don't bother with that. So I will merge this pull request.

I'm only using https://marketplace.visualstudio.com/items?itemName=open-southeners.laravel-pint atm.

**Comment by lorenzomigliorero** [comment]
Thanks! And for debugging, I must have a [ray](https://spatie.be/products/ray) license, right?

**Comment by andrasbacsai** [comment]
I have made the settings in the next version, so I will also merge this. Thanks for the PR!

**Pull request merged**
