### PR TITLE
ui: Fixed z-index for magicbar

### PR DESCRIPTION
**Pull request by chz**
#1240 Fixed issue magicbar z-index.

Added z-index

### CODE REVIEW

**Comment by andrasbacsai** [comment]
Haha, thanks! 

I tried to solve it in 10 minutes, but I gave up. You probably spent more time opening the PR than solving the problem. 😄

**Comment by chz** [comment]
> Haha, thanks!
> 
> I tried to solve it in 10 minutes, but I gave up. You probably spent more time opening the PR than solving the problem. 😄

Yeap, btw if anything is incorrect with PR let me know. I. will do my best for next PR's ))

**Comment by andrasbacsai** [comment]
It looks good and works. That is more than enough.

**Comment by chz** [comment]
> It looks good and works. That is more than enough.

no i mean next time i must create branch from next or main branch?

**Pull request merged**
