### PR TITLE
Feat: Add Docker notification logic to health check #2332

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #2332
Fixes: #2332 

Summary:
This PR adds a notification mechanism for health check status changes in the ApplicationDeploymentJob class.

Changes:

Notification Logic:

Added sendDockerNotification method to log and send Docker events for health status changes.
Integrated this method into the health_check function to detect and notify on status changes.
File Modified:

src/Jobs/ApplicationDeploymentJob.php: Added notification logic and ensured proper placement.
Testing:

Added and executed unit tests.
Performed manual testing to verify functionality.

### CODE REVIEW

**Comment by Anshgrover23** [comment]
@cmer @wutangpaul @AshKyd @mauvehed plss review the pr

**Comment by EinfachHans** [comment]
Ok from now on we have to wait until andras reviews 😊 whenever he approves & merges the pr the bounty is rewarded. Thank you so far already!

**Comment by Anshgrover23** [comment]
@EinfachHans ok thanks for helping me in everything

**Comment by alexzvn** [comment]
Quick reminder, your PR should merge to coolify `next` branch

**Comment by Anshgrover23** [comment]
@alexzvn ok so do i have to do anything because sorry i dont get your comment? can u  plss elaborate

**Comment by EinfachHans** [comment]
@Anshgrover23 you have to adjust your pr' target branch, which currently points to the `main` branch

**Comment by Anshgrover23** [comment]
@EinfachHans @alexzvn ok doing it

**Comment by Anshgrover23** [comment]
@alexzvn hi alex done changed the target  branch

**Comment by Anshgrover23** [comment]
@andrasbacsai @alexzvn done all changes ready for merge

**Comment by Anshgrover23** [comment]
@EinfachHans when will it get merged may I know the reason why no one is viewing my pr?

**Comment by Anshgrover23** [comment]
@EinfachHans @andrasbacsai is there anything wrong?

**Comment by EinfachHans** [comment]
@Anshgrover23 Stop spamming please... Andras is running coolify alone. He will review the pr whenever he has the time for it. Tagging him or anyone else is not helping in any way. Just wait ✌🏼

**Comment by Anshgrover23** [comment]
@EinfachHans ok sorry for spamming

**Comment by Anshgrover23** [comment]
@EinfachHans can i ask you a question when will i rewarded that bounty because i thought the andras will ckeck it and i will get it or i have to make more changes to this pr i it so?

**Comment by EinfachHans** [comment]
@Anshgrover23 the bounty is rewarded when the pr is merged. If you have to do more changes, i can not tell you. You have to wait for andras review.

**Comment by Anshgrover23** [comment]
@EinfachHans ok bro.

**Pull request closed without merging**
