### PR TITLE
[TEMPLATE] Forgejo template (with single runner)

### PR DESCRIPTION
**Pull request by DarkGhostHunter**
This PR adds Forgejo as a service. Since [Forgejo](https://forgejo.org/) also supports first-party runners (on alpha), it includes versions with a single runner.

Runners are not critical for the service, so this PR may be approved partially. Also, runners can be also registered to Forgejo through App Tokens and OAuth2, like DroneCI does with Gitea.

There is a waiting [PR ready to be made to the documentation](https://github.com/DarkGhostHunter/documentation-coolify/tree/feat-forgejo).

Also, all my homies hate gitea.

(This is a retry of #2715 but to the correct branch)

### CODE REVIEW

**Comment by carbontwelve** [comment]
Is this missing the `forgejo.svg` file?

**Comment by DarkGhostHunter** [comment]
> Is this missing the `forgejo.svg` file?

You're right! Totally forgot that. It should be the F, gonna look for it.

**Comment by peaklabs-dev** [comment]
Thank you for the PR 💜. This is a huge one than you so much, I will test it and fix it if necessary.

**Comment by DarkGhostHunter** [comment]
By the way, the PR for documentation is here: https://github.com/coollabsio/documentation-coolify/pull/45

**Comment by peaklabs-dev** [comment]
Thanks for the docs PR.

**Pull request merged**
