### PR TITLE
New services: LLM & AI-related one-click services

### PR DESCRIPTION
**Pull request by rennokki**
## Reasoning

I added these as the LLM/AI domain started to be more complex and vast in the self-hosted communities.

## Checklist

- [x] ~Dify.ai (+ variants with Qdrant, Weaviate)~ — #3074
- [x] **Langfuse** — Langfuse is an open-source LLM engineering platform that helps teams collaboratively debug, analyze, and iterate on their LLM applications.
- [x] **LiteLLM** — Call all LLM APIs using the OpenAI format. Use Bedrock, Azure, OpenAI, Cohere, Anthropic, Ollama, Sagemaker, HuggingFace, Replicate, Groq (100+ LLMs)
- [x] **Prefect** — Prefect is an orchestration and observability platform that empowers developers to build and scale workflows quickly.
- [x] **Unstructured** — Unstructured provides a platform and tools to ingest and process unstructured documents for Retrieval Augmented Generation (RAG) and model fine-tuning.
- [x] **SearXNG** — SearXNG is a free internet metasearch engine which aggregates results from more than 70 search services.
- [x] **AnythingLLM** — AnythingLLM is the easiest to use, all-in-one AI application that can do RAG, AI Agents, and much more with no code or infrastructure headaches.
- [x] **Infisical** — Infisical is the open source secret management platform that developers use to centralize their application configuration and secrets like API keys and database credentials.
- [x] **Weaviate** — Weaviate is an open-source vector database that stores both objects and vectors, allowing for combining vector search with structured filtering.
- [x] **Qdrant** — Qdrant is a vector similarity search engine that provides a production-ready service with a convenient API to store, search, and manage points (i.e. vectors) with an additional payload.
- [x] **Argilla** — Argilla is a collaboration tool for AI engineers and domain experts who need to build high-quality datasets for their projects.

## Other services

I will add some more in other PRs. For now, this is it, with the following upcoming:

- LabelStudio
- ZEP
- ArangoDB (Langgraph)
- MageAI
- Flowise

### CODE REVIEW

**Comment by therealtimex** [comment]
Propose to add ComfyUI https://github.com/comfyanonymous/ComfyUI

**Comment by OhThatMatt** [comment]
Just spotted this, I have added Dify template in this PR: #3074

**Comment by rennokki** [comment]
@OhThatMatt Thanks. Is it possible to join and make some changes to that PR if it is okay with you?

**Comment by Timopheym** [comment]
Thanks a lot for taking langfuse in! 

Shall we may be split this PR into multiple in favour of speed of integration?
given the fact of speed of those products development speed, version of Langfuse could obsolete at the moment of merge

**Comment by peaklabs-dev** [comment]
This pull request is currently in draft status. We would like to merge the currently available changes, please take the PR out of draft status. If no action is taken, this PR will be closed for inactivity.

**Comment by rennokki** [comment]
@peaklabs-dev @andrasbacsai

**Comment by peaklabs-dev** [comment]
@rennokki wow insane work 🎉

**Comment by andrasbacsai** [comment]
I will merge this and test as much as I could. Thanks for the PR!

(next time, please open 1 service / PR, easier to review and everything).

**Comment by Skeyelab** [comment]
@rennokki - I know this PR is closed, but I am having issues with anythingLLM out of the box.  

Whenever you restart the application, I need to go back to Settings > LLm and rechoose my selection.  

Anyone else experience this?

**Comment by jeffscottward** [comment]
> @rennokki - I know this PR is closed, but I am having issues with anythingLLM out of the box.
> 
> Whenever you restart the application, I need to go back to Settings > LLm and rechoose my selection.
> 
> Anyone else experience this?

How are you even getting in in the first place? Question mark. When I deploy and go to the URL, it just has a password box, but no way to sign up.

**Comment by ekiwi111** [comment]
I'm getting a 404 error from `/console/api/setup` on the `/install` page when running Dify with the Docker Compose template. Is there any additional configuration I need to add?

**Comment by rennokki** [comment]
> @rennokki - I know this PR is closed, but I am having issues with anythingLLM out of the box.
> 
> Whenever you restart the application, I need to go back to Settings > LLm and rechoose my selection.
> 
> Anyone else experience this?

Set your settings by creating new environment variables in the template. See https://github.com/Mintplex-Labs/anything-llm/issues/2307#issuecomment-2359428503 and [the .env file](https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/.env.example)

**Pull request merged**
